### ISSUE TITLE
Shotguns and Heavy Zombie Shenanigans

### ISSUE THREAD

**Issue by mega00913** [HelixNebulaStudio/RiseOfTheDead#118]
While my quiche is baking in the oven I checked out the new shotgun-breaking-off-limbs feature, and it did not disappoint :)

**Issue:**
The upper body of a `Heavy Zombie` can be blasted off without killing them, creating something rather uncanny.
Currently this issue only concerns said zombie type, and so far I cannot replicate this on others.

**Extra Comments / Suggestions:**
If the arms of a `Heavy Zombie` are shot off, I think their throw ability should be disabled. I mean how are you supposed to throw another zombie without arms?
Similarly, when the legs of a zombie are blown off, should they stop moving? Or they could instead switch to some crawling animation? Something like this could be fun - imaging crippling a `Tick Zombie` with shotguns...

My quiche finished baking so before I go I'm humbly inviting @MrPigZ for his help towards this issue as I feel like he's the expert in this field... especially for something so suspicious.

---
Attached are screenshots as well as a short video demonstrating the issue:
https://www.youtube.com/watch?v=jjIMEHRmVzs

![wow](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162569959/93041331-51c0-4735-b35f-fa5158e8c65b)
![grab](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162569959/6f167e4c-11ac-47b9-9ec4-2174d85f09c3)

**Comment by Speedycar777** [comment]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/a6452eb6-0dbb-4ae9-b245-b580bab32345)
it can go all the way to just its waist and not die

**Comment by MrPigZ** [comment]
Unfortunately it seems like I am too late. I am not even able to shoot any limbs off a lvl 1 heavy with a lvl 0 xm1014.

**Comment by MXKhronos** [comment]
Fixed in f647ed093641d625aa7e0e585072b08dc1ff0e48, 0b2a3b2aff377b467286f6c558e63e3b37ffc180 and fixed the check for when torso joints should break.
