### ISSUE TITLE
Naturally drowning causes a script to run multiple times

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#12]
Seems to be a reoccuring issue where this bug spawns multiple instances of grey player models when they do drown by running out of air. These models can only be seen by other players and not by the player who drowned. It also duplicates UI icons such as inventory Icons.

Seems like players keep losing health after drowning effectively dying multiple times and forcing a respawn script to ininiate multiple times.

![Schermopname (11542)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/4c67b90b-0763-49d4-aecb-459990bec556)

**Comment by MXKhronos** [comment]
Oh, yeah, this was fixed in dev-branch.
