### ISSUE TITLE
Black box teleportation

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#124]
Interacting with boss or extreme boss gates will ocsasionally teleport the player in a black box (the boss lobby).
![Schermopname (11922)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/74fb47a4-964b-4202-9d13-1b2096fdd647)

It is not possible to leave this box without reseting. Using the GPS while in it will let the player teleport to the selected destination, but will not grant them the ability to move. 

Console shows nothing. This is also a reoccuring issue.

**Comment by MXKhronos** [comment]
Will close for now, console should give some indication on what went wrong if it happens again so I can figure out a solution. Reopen when that happens.
