### ISSUE TITLE
List of entities that should despawn upon death

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#126]
A few enemies should despawn instead of keeping their ragdoll / body in the world. For example most bosses don't really have an idle animation so they always turn into stiff brick-like poses.

Entities that should despawn:

All extreme bosses (especially zricera and bandit heli)
All bosses (especially Fumes)
All mini bosses

Some of these entities spawn accompanied with a little sound, like for example Fumes' flies or Zricera's burning flame.

**Comment by Leroy8888** [comment]
As a side note, maybe collision with the ragdolls should be turned off from all enemies.

**Comment by MrPigZ** [comment]
I would like to add the blockage parts in sunken ship
