### ISSUE TITLE
Tool handler error in dev console log

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#13]
I am not sure what causes this error to occur or what it exactly seems to effect, but it does seem to spam itself in the console whenever the tool, in this case the testers sword, collides with another entity such as a zombie.
![Schermopname (11543)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/3daa4931-3c94-4d2d-bbd7-0516dd60df76)

**Comment by MXKhronos** [comment]
This should be fixed. It's probably related to the drowning bug because it's attempting to get a specific UI component but the multiple respawning destroyed it.
