### ISSUE TITLE
Ammo recycler doesn't refund ammo

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#14]
I unfortunately do not have much info regarding this issue as I haven't been able to replicate it yet, but according to the person who reported it, it often occurs when joining a new server most notably in residentials.

The developer console does not seem to show anything regarding the issue.

(https://medal.tv/games/roblox/clips/20vMzKaBQ6QOxC/d1337GUzvXxE?invite=cr-MSw4MWMsMjA5NzYxMDAxLA)
The player was not at the ammo cap when this issue occured.

I'll leave this as an issue open for input of anyone who does run across the same issue.

**Comment by JakobCh** [comment]
might have something to do with the fact that residentials gets laggy after a while, notice server uptime of 9 hours in the video.

**Comment by MXKhronos** [comment]
Fixed, it now can give you ammo exceeding your ammo capacity.
