### ISSUE TITLE
Zombie spawns.

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#142]
Are there supposed to be this many zombies spawning in full servers? It seems to be a little bit extreme.
![Schermopname (11977)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/efa9d982-9f7c-4a69-9657-c2e5911bc2df)

**Comment by MrGarrettFerret** [comment]
This seems to be causing a LOT of lag too.

**Comment by Leroy8888** [comment]
The lag is definitely the biggest issue atm.
