### ISSUE TITLE
Can't interact with the Belly of the Beast chest during Sunken Salvage

### ISSUE THREAD

**Issue by JakobCh** [HelixNebulaStudio/RiseOfTheDead#149]
I tried rejoining the map and it still wouldn't let me interact with it.
![RobloxScreenShot20240413_113242571](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/21bbe125-ef0f-4a8f-a195-333e976a6c03)

**Comment by JakobCh** [comment]
Another user on the unofficial discord also reported that this happened to them.

I managed to complete sunken salvage by interacting with the normal crate sticking out of the back, but Belly of the Beast remains uncompleted.

**Comment by MXKhronos** [comment]
If anyone experience this issue, the console should now have some extra information for me to debug this.
