### ISSUE TITLE
The Prisoner Reworked

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#15]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/1d3ada7b048364b23ebd41f5255c7e43f8e30471

## Updated `The Prisoner` behavior.

- No longer spawns jail cells, instead, you are chained to an anchor when attacked by the prisoner. The anchors can be destroyed to break free of the chains.
- Can sprint for 1.5s every 6s if not in range to attack player.
- Can equips a `survivalknife` when it's `< 50%` health which increases its attack speed from 2.3s to 1s.

- Anchors have 100hp (Hard: 2000hp)
- Chain's length is 32units (Hard: 20units)
- You can be chained multiple times.

**Comment by MXKhronos** [comment]
> If player leaves the room while chained they will go out of bounds. I would like to suggest that the chains despawn when the boss dies.

Fixed, chains should now be destroyed when The Prisoner is dead.
Chained status effect should also now disapear if the player is no longer chained.

**Comment by MXKhronos** [comment]
Oops accidentally closed the issue, reopened for more feedback.

**Comment by Leroy8888** [comment]
The Prisoner seems to work fine, although it's surprisingly easy to cheese the boss since jumping on its head will cause it to stop attacking.

The anchors also occasionally seem to attack a visible rope to the player.
![Schermopname (11609)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/200c3325-0ffe-474e-9229-630e04e14a00)

**Comment by MXKhronos** [comment]
Fixed rope visibility. Increased The Prisoner attack range. Chained anchors are now movable with enough force.

**Comment by MrPigZ** [comment]
The chains now makes player movement super laggy.

**Comment by MXKhronos** [comment]
> The chains now makes player movement super laggy.

Should be fixed now.

**Comment by Leroy8888** [comment]
When chained, using the GPS will teleport the player to said location for a split second, which is enough ''force'' to drag the anchors into the void. Doing it again will result in the anchors pulling the player into the void for the duration of the effect. [https://gyazo.com/f7a71a9f4837d4a9f6e7ec39cb59b51a](url)

**Comment by MXKhronos** [comment]
> When chained, using the GPS will teleport the player to said location for a split second, which is enough ''force'' to drag the anchors into the void. Doing it again will result in the anchors pulling the player into the void for the duration of the effect. https://gyazo.com/f7a71a9f4837d4a9f6e7ec39cb59b51a

Should be fixed now.
