### ISSUE TITLE
Warmonger mod works in combination with the health mod

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#162]

**Comment by MrPigZ** [comment]
They still can work together.

look at this picture
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/6726472c-8dba-4d33-9222-d9b12b53f49d)

**Comment by Leroy8888** [comment]
Also works with armor mods. So you can have health, armor and warmonger all active

**Comment by GregTheBestest** [comment]
250 health and 80 armor points is something that keeps players alive at later waves in survivals
