### ISSUE TITLE
If player is doing rapid movements, pat with a bow will shoot the arrow to a shadowzone

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#176]
So basically pat wastes ammo while firering nothing.
This issue is way more noticable on tactical bow than on crossbow

**Comment by MXKhronos** [comment]
That's probably going to be a thing for any projectile weapons because they all have their own projectile travel time. I could maybe add a setting on the Pat to only fire when player's not movement rapidly.
