### ISSUE TITLE
`TheWarehouse` Streaming Enabled

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#177]
I've enabled streaming for `TheWarehouse` place.

This means:
- Far away models will load in and out if you are low on memory. Minimum radius is 64 units, max is 1024 units.
- Client side cutscene sequences relying on some models may be affected.

If anyone come across issues with mission cutscenes or models like zombies not functioning normally after popping in, let me know here.

**Comment by Leroy8888** [comment]
#185

**Comment by Leroy8888** [comment]
It seems like it's more common now to run across low quality objects as a result of SteamingMesh. It also does seem to depend on where the players spawn in the world when joining it. A few examples can be seen below.
![Schermopname (12047)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/e6004280-4d4c-4fd8-ba12-29ce084877c6)
![Schermopname (12049)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/13775295-169a-4bf8-8e44-05fbf3c9daba)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/9a819f8e-d8eb-4618-9532-eadefc61ae4c)

**Comment by MXKhronos** [comment]
Hmm, it should supposedly swap out the low res version with the real model when you're up close. It's should be how Level Of Details (Lod) works.

**Comment by MXKhronos** [comment]
All public worlds are now streaming enabled, however I haven't configured any new models to be a StreamingMesh.
