### ISSUE TITLE
The ''billboard'' in warehouse looks a bit, odd.

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#185]
But on the plus side, if you do see it then it does catch your attention.

![Schermopname (12031)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/c1bf3666-68d5-449f-b046-d6245a9b2e88)
![Schermopname (12032)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/912b41f2-48bd-4627-b9c7-05baad7c3a25)

**Comment by MXKhronos** [comment]
It's using StreamingMesh as the level of detail, it seems like the "imposter" mesh is even lower resolution than expected. More adjustments will be made in the future. https://create.roblox.com/docs/en-us/reference/engine/classes/Model#LevelOfDetail
