### ISSUE TITLE
Portable Auto Turret

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#19]
ItemId: `portableautoturret`

A wearable portable auto turret designed by the Mysterious Engineer. Requires batteries to run. Configure to equipped your weapon onto the arm and fine tune the P.A.T. to how you want it to function, but due to it's crude nature, the arm's aim accuracy can be underwhelming and reload times are 3x as slow.

‌

- Aim is roughly x3 the weapon’s base inaccuracy, but scales diminishingly. E.g. LMG and shotgun inaccuracy won’t be x3 and more like x1.05. Ammo cap mods are
- Reload time is x3. This can be remedied with reload speed mods on the weapon.
- You can directly select the PAT in shop and resupply stations to refill the weapon within.

### PAT Configurations

You’re the engineer, configure the PAT to how you see fit to your use case.

- Use it as a dedicated anti-immunity support by enabling **Toxic Barrage Mode** and **Debuff Only**.
- If you have configuration suggestions let me know and I’ll see if it’s possible to work in.

---

### Endurance Skill: Energy Conservationer

Reduce battery power drain cost (10-85%).

- Since the PAT will require batteries. This new skill will reduce the power drain for the battery.

---

### Authority Skill: Machine Aim Stablizer

Increase devices such as the Portable Auto Turret aim stability by (5-30)%.

- Since the PAT’s accuracy is x3, this will reduce the multiplier by up the 30%.

---
No more additions to the PAT for now.

**Comment by JakobCh** [comment]
It seems to stop firing when it runs out of reserve ammo on the shotguns, even tho they still have ammo in the magazine.
Tested on both the Rusty 48 and Mariner 590.
If you turn it on again after it will fire for like a second before turning off again.

**Comment by MXKhronos** [comment]
> It seems to stop firing when it runs out of reserve ammo on the shotguns, even tho they still have ammo in the magazine. Tested on both the Rusty 48 and Mariner 590. If you turn it on again after it will fire for like a second before turning off again.

Should be fixed now.

**Comment by JakobCh** [comment]
If you have crowd firing mode on it won't reload if there isn't enough zombies around you to fire.
It does reload if you get away from them.
I was using the at4 when I noticed this.

**Comment by MXKhronos** [comment]
> If you have crowd firing mode on it won't reload if there isn't enough zombies around you to fire. It does reload if you get away from them. I was using the at4 when I noticed this.

Should be fixed now.

**Comment by Leroy8888** [comment]
It's been around for a while now, but I figured I do mention it since it's still a thing.

Some fixed have been pushed regarding the fire rate cap, but it does still increase the fire rate over the cap the weapon can shoot at. It always occurs when the selected cap is above the max fire rate of the weapon.

When a fire rate cap below said max fire rate of the weapon is select it is often ignored. When it is not ignored it will proceed to shoot mutliple rounds as if it fired above the selected fire rate cap, but these ''shadow bullets'' won't deal damage. They will however drain the magazine of the weapon.

**Comment by JakobCh** [comment]
If you're fighting Jaws it seems to shoot where it last was above ground while it's underground.

**Comment by MXKhronos** [comment]
> If you're fighting Jaws it seems to shoot where it last was above ground while it's underground.

Jaws is not longer detectable by the PAT
