### ISSUE TITLE
Last Missing Blueprint Piece doesn't spawn inside Eaten Sunken Crate 

### ISSUE THREAD

**Issue by Qureejjang** [HelixNebulaStudio/RiseOfTheDead#194]
During the Belly of the Beast mission, the part where you need to do "Sunken Salvages", the chest does not spawn in the missing blueprint piece. During the "Sunken Salvages" mission, you will only be able to find 2 of the chests then the eaten sunken chest which gives you nothing. Leaving and rejoining will give you the last sunken chest for your "Sunken Salvages" mission but won't complete your initial mission. (This isn't the same for everybody)

**Comment by MXKhronos** [comment]
Reopen if there are still signs of occuring.
