### ISSUE TITLE
Nekros trench coat doesnt heal me after 15 seconds of no damage

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#200]
the trench coat broke right now and it aint healing players anymore after 15 seconds of taking no damage

**Comment by SaibotAppend** [comment]
Same ,even not works from amplifying Nekrosis effect mods too

**Comment by SaibotAppend** [comment]
![image_2024-04-17_103339640](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/167265144/0151471f-efdc-4b08-bc97-601ad3c5234b)
Now that's the problem...
