### ISSUE TITLE
Stackable resources problematics.

### ISSUE THREAD

**Issue by SaibotAppend** [HelixNebulaStudio/RiseOfTheDead#202]
Stackable resources such as clothes ,metals ,glasses ,woods ,even NEKRON SCALES dont stacks each others to the same resources in inventories.

**Comment by KatMeowChi** [comment]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/167261999/27540398-feed-4ceb-82bd-f3152cfc5686)

**Comment by SaibotAppend** [comment]
Yes that one...

**Comment by SaibotAppend** [comment]
![image_2024-04-17_102432412](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/167265144/fbc101e3-7c67-4e38-9227-f7903aa8211e)

Nice try... Explain this

**Comment by KatMeowChi** [comment]
Explain what? I have the same issue and I was trying to give some lead to where it is.

**Comment by SaibotAppend** [comment]
let me try... plus Nekrosis Mod and passive effect of Nekron Trench Coat has an issue

**Comment by SaibotAppend** [comment]
Okay it is still function when do shift-click
