### ISSUE TITLE
Sunken Ship Arena not being shown correctly 

### ISSUE THREAD

**Issue by Qureejjang** [HelixNebulaStudio/RiseOfTheDead#204]
When entering the Sunken Ship coop arena, it doesn't showcase the proper location but showcases the underwater brick of where your character teleports to when inside. Teleport function works normal, visually bugged. 
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162429221/0dc3f5b6-c675-4aa8-8b81-4cc8d50973c1)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162429221/179ec58d-58ed-49ae-99cf-ba0aed10a426)

**Comment by MXKhronos** [comment]
Related to a previous issue with game lobbies. Should be fixed now.
