### ISSUE TITLE
Zombies doesnt spawn in warehouse

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#206]
This bug has been repeated. MrPigZ posted first but it seems it got repeated. it can make new players can't progress their core missions due to no zombies spawning

I don't know whats the causes of it but i commonly encounter this in older servers. but in newer servers its working fine
![Screenshot (117)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/beb78ac8-b8ee-4d9d-ad00-ec8a71d38569)
![Screenshot (118)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/e272e2b7-4ff1-407d-8a67-8b873b50757b)

**Comment by Leroy8888** [comment]
I'll have to quickly confirm whether this issue is exactly the same as the one submitted by PigZ, will close it if it seems to be.

**Comment by Leroy8888** [comment]
I was unable to encounter this issue in any of the public servers. Were there any unusual occurances when you ran across this issue?

**Comment by Leroy8888** [comment]
Closed as this does not seem to occur anymore.
