### ISSUE TITLE
Bunny mask doesnt work during easter

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#207]
A player told me that bunny mask doesnt work but its still easter

**Comment by Rookie21333** [comment]
![Uploading Screenshot (119).png…]()

**Comment by Leroy8888** [comment]
You might want to re upload that screenshot since it appears you send the message before it was fully uploaded.

**Comment by Rookie21333** [comment]
![Screenshot (119)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/b4e8dad8-e86a-49cc-86ee-ef34db5d1018)
