### ISSUE TITLE
Ammo desync on AT4

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#208]
This issue got send to me from an anonymous user via Damion. I unfortunately have no background how to replicate it as I wasn't able to.

https://medal.tv/games/roblox/clips/27LLFFBRzyZolG/d13378angrsc?invite=cr-MSxnTXgsMTkxNTE0NDQ2LA

**Comment by MXKhronos** [comment]
This was fixed here. https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/f491707ea292c3d3329cde5702f7d56d63197e30
