### ISSUE TITLE
Tanker Reworked

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#22]
Updated Tanker Appearance and Behavior.

- `Tanker` doesn't have a basic attack. He will just follow you.
- `Tanker` Rebar Slam: Slams the rebar on to the ground, doing 45(Hard: 200) damage knocking away nearby players and creates a wall of rebars. Blocking off a path. 
- `Tanker` Rebar Tornado: Tanker spins the concrete rebar and moves faster. Doing 5(Hard: 10) damage per 0.5s.
- Enabled Hard Mode for `Boss: Tanker`

**Comment by MXKhronos** [comment]
Polished up some actions. https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/eb73f530e993201c81c476f11db87a82459e9aeb

**Comment by MrPigZ** [comment]
Tanker stands still during its first Rebar Tornado.

**Comment by MXKhronos** [comment]
Tanker should now start by following the player first.

**Comment by MrPigZ** [comment]
Tanker still stands still during its first Rebar Tornado.

**Comment by MXKhronos** [comment]
Should be fixed now.
