### ISSUE TITLE
Effect bubles radius broken

### ISSUE THREAD

**Issue by 751234** [HelixNebulaStudio/RiseOfTheDead#220]
For example, bubles like the bloaters ones, the bubble that hector shot creates to lasso you, etc. These bubbles radius is broken and even you if are standing outside it you will be affected by it.

**Comment by Leroy8888** [comment]
The one with hector shot is an issue where the radius of the lasso moves as he moves. It just isn't visible. 

for the bloater issue, refer to issue #183

**Comment by MXKhronos** [comment]
Bloater's gas hitbox have been improved.
