### ISSUE TITLE
Dr. Sinister now affects ticks zombies

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#230]
on the older version of rotd, Dr. Sin gives zombies immunities but ticks are excluded. but in this current version they affects ticks now.

idk if this is a bug or it was intended so i need some answers

**Comment by MXKhronos** [comment]
It is intended to make things a bit more consistent, if the ticks are too strong because of that I could make it do less damage if they are immune.
