### ISSUE TITLE
P.A.T battery and weapon is none even though there is

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#236]
The P.A.T says there so no battery and weapon in it but there is and i cant really buy ammo for my weapon in it. the only way to fix this is to remove and add the weapon or battery to the PAT
you can also see there is a desolator from the PAT of my character

![Screenshot (126)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/8d54863b-7530-4346-bad5-b31798e11222)

**Comment by Speedycar777** [comment]
From what I've tested with it before it just hasn't loaded the data inside of it until it has been opened so when its opened it fixes.

**Comment by MXKhronos** [comment]
Related https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/cb2f4599c85dd12cbd28510ea9bf556a9559d245
