### ISSUE TITLE
Bandit heli stops functioning

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#247]
Either on normal or hardcore, after enough time has passed during the battle the heli will fly off to drop molotovs.

When it does so however, the heli will instead freeze in place, drop the molotovs and stop functioning all together.

This only occurs if enough time has passed and go in for the molotov run. It does not occur if the gunmen are killed as that seems to reset the timer.

**Comment by choppygraph** [comment]
Can confirm.
Tried out the normal helicopter in the main branch, shot it a few times and it did a molotov run, then just froze in place not doing anything as mentioned.
However once I killed it, the heli rapidly accelerated toward the other end of the arena and stayed there until it despawned.
