### ISSUE TITLE
The elevator in harbour doesnt work.

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#254]
![Screenshot (145)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/2a0ed663-fa46-4e06-8fb4-033bb303c212)

**Comment by choppygraph** [comment]
Can confirm.
Never seen a working lift in any public server older than an hour,
Always works in fresh private servers.
