### ISSUE TITLE
Blue book can be picked up twice

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#255]
During ''Stephanie's Book'' the book respawns once collected. This allows the player to pick up 2 books.

1 book will be removed from the players inventory after completing the mission, the other one will stay and cannot be deleted.

**Comment by choppygraph** [comment]
Can confirm, saw this happen in dev branch.

**Comment by MXKhronos** [comment]
+ You can now talk to Stephanie to give her the extra blue book.
