### ISSUE TITLE
Premium Tax involved...

### ISSUE THREAD

**Issue by SaibotAppend** [HelixNebulaStudio/RiseOfTheDead#261]
I have bought... Premium Gamepass ,but when attempting to trade with guns or mods ,it is still costs Gold with Non-Premium Tax ,even I have Premium Gamepass. Can you explains this?

**Comment by SaibotAppend** [comment]
![Uploading Screenshot 2024-05-04 134402.png…]()

**Comment by SaibotAppend** [comment]
![Screenshot 2024-05-04 134402](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/167265144/a76ec611-b803-4996-ab57-70c0c8576989)

**Comment by rafaderren** [comment]
The other person doesn't own premium, there will be tax if at least one person doesn't own premium, both are required to have premium to avoid gold tax
