### ISSUE TITLE
The current zombie don't look like a player wearing a nekron mask

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#262]
![Screenshot (155)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/bc1e53d1-6831-4df9-ac81-9c495fe7d73a)
![Screenshot (156)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/f92fabd5-c37a-40e5-a93a-2a18c6069a49)

**Comment by Rookie21333** [comment]
it only copy your hats ( or hair)

**Comment by Leroy8888** [comment]
I am pretty sure this is intentional, but i'll leave it open for now.
