### ISSUE TITLE
Crash in public servers

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#269]
Unfortunately I am not quite sure what causes this one and have no leads on anything, but seeing how common this issue is i figured I'll at least open an issue about it.

It occurs pretty frequently in public warehouse servers, but can also occur in other worlds.

**Comment by MXKhronos** [comment]
These crashes are client side scripts that in rare cases gets stuck in infinite loops. I added crash protection to some cases I found that seems to have the possibility to cause a crash. We'll see if they were the actual cause of the crashes eventually.
