### ISSUE TITLE
Misspelled weapon parts in the workbench customization menu

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#272]

**Comment by Leroy8888** [comment]
Instead of opening a new issue, i'll just reopen this one as it appears these spelling error are present in a few more weapons, namely;

**Rec-21**
- Barral
- Barralguard

**Arelshiftcross**
- Hand Gaurd

**Spotlight**
- _lightSource

Some of these also do not have capitals,
**VectorX**
- bullet
- mbullet

**Arelshiftcross**
- Riser screws
- Body mount
- Stock part

**Comment by MXKhronos** [comment]
Updated part names and visibility on workbench.
