### ISSUE TITLE
Zombies spawn in objects or the ground

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#274]
https://cdn.discordapp.com/attachments/1233359403302912131/1233359404087250944/Roblox_2024-04-26_19-43-55.mp4?ex=663bf834&is=663aa6b4&hm=25b7ad7a8d75d5f9b1e909b379dc7954383a58fc0e0a14e21380f07e3ce7ab8d&

**Comment by MXKhronos** [comment]
Increased spawn height offset.
