### ISSUE TITLE
Boss lobbies always show the first lobby

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#275]
When entering a lobby for a boss, the first room will always be shown, regardless whether the room is joinable.

A QoL change should be made to check if there are any joinable rooms and then redirect the player to those instead.

This also was a feature prior to the 2.0.0. update, which means this likely is a bug.

**Comment by MXKhronos** [comment]
Should be fixed along with this commit: https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/0a8537f1468d1f582ea0f90b640dfe765bd6e01e
