### ISSUE TITLE
Safehomes fail to keep track of the safehome capacity

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#282]
When a player kicks out a survivor out of their safehome the game won't actually properly update the safehome (survivor) capacity. 

This issue prevents the board mission ''another survivor'' from cycling through it.

This issue might be important to fix before the update releases as it's very likely that many people will kick out at least one survivor in order to roll Lydia in the survivortable.

![Schermopname (12452)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/58cf4f5f-42db-4bf4-b422-ed5ca37b00ee)
Unsure if the screenshot above has to do anything with the issue, but it might be connected.

**Comment by MXKhronos** [comment]
I can't seem to replicate this in dev-branch, if you also experience this in dev-branch, could you let me know the steps it took to replicate it? If it's not reproducible, it may be fixed already.

**Comment by Leroy8888** [comment]
I did actually report this directly from dev branch. 

The safehome survivor capacity has to be full first. After kicking a survivor, the ''another survivor'' won't appear on the mission board, despite the there being capacity. This only seems to occur once the player leaves safehome and there are no further additional steps in between to replicate the issue as far as I am aware.

That or I've gotten very unlucky trying to replicate this issue, as I've skipped over about 40 missions and ''another survivor'' didn't appear while other missions repeatedly did.

**Comment by MXKhronos** [comment]
Ah, I just noticed that `Another Survivor` has a add cooldown of 4 hours, so that may be why you're not getting the mission.
https://github.com/HelixNebulaStudio/RiseOfTheDead/blob/86c7c794bdaed615defb7a69f4333b3c89f0efb0/Source/Client/MissionLibrary.lua#L1894C1-L1922C3

**Comment by Leroy8888** [comment]
The issue this player was experiecing has been resolved after a bit of digging. 

It appears this player was stuck on **replaying** `Something's Not Right` which possibly caused this issue, which at the time of the report was not known. 

Leaving this here as a note
