### ISSUE TITLE
The electrical charge mod provides incorrect damage values

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#283]
The mod states that a certain damage value is used to calculate the output based on the premod damage. However, on all levels the damage output is the stated output -2%. This includes sums with tweak bonuses. E.g. +6% from a tier 3 tweak on a partially upgraded mod (14%) would deal 18% (20% - 2%) of the premod damage as electric damage.

**Comment by MXKhronos** [comment]
Oh, for every electric bounce the damage is reduced by 2%.
