### ISSUE TITLE
Faction menu refuses to load.

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#287]
A particular player and faction has been experiencing issues with loading their faction menu. They cannot open it as it gets stuck on the loading screen. This also makes it impossible for the player to leave the faction.

Replication of this is unknown, but it seems like the anticheat is involved for some reason in this.

Faction tag of the effected faction: (pending)

An error pops up in the console whenever an attempt is made to open the faction menu, being; 
![bd8411684fff09c67e3cf5551d91e29f](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/fa4665bb-c6e1-4f35-855d-eedc875d9f79)

**Comment by MXKhronos** [comment]
Fixed in dev branch.
