### ISSUE TITLE
Mounted weapons cannot be refilled when mounted in the PaT

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#288]
When a weapon is mounted they can be refilled, but upon entering a new world they cannot be anymore even if they used some ammo.

This can be solved by taking the weapon out of the PaT and then mount it on the PaT again. It is quite the nuisance when grinding raids or other places that require the player to travel between worlds.

**Comment by Speedycar777** [comment]
You can just open the pat and close it and it fixes, but it is a very mild nuisance when you need to.
