### ISSUE TITLE
Chinematic mode crosshair

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#29]
Enabling this mode disables most of the HUD, but it doesn't seem to disable the crosshair which gets in the way if you try to take a shot in said mode.

**Comment by JakobCh** [comment]
I noticed that cinematic mode hides the ammo counter but if you only use the toggle hud keybind the ammo counter stays on screen.

**Comment by MXKhronos** [comment]
Cinematic mode hides most information hud but crosshair will remain, but toggling hud now also hides crosshair.
