### ISSUE TITLE
The fish model in the Canned Sardines tin clips through the tin while eating

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#294]
When using Canned Sardines, small dark pointed parts appear on the left side of the tin before each fish is taken out of the tin and after each fish is 'eaten'. Additionally, it is possible to see the 'eaten' fishes quickly move back inside of the tin shortly after they are 'eaten' (although this may occasionally occur too quickly to see).

This can be avoided by not attempting to eat Canned Sardines.

This was observed while playing the game on a computer.

The version on which this was observed is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/f6e61c43-2209-480a-8bd2-875cccf38fa2
https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/c68cef43-7ede-4ecd-b5ac-8569f06ab395

**Comment by MXKhronos** [comment]
Added SetTransparency markers to animation for fish.
