### ISSUE TITLE
Travelling from W.D. Residentials to W.D. Underground using the entrance has a chance of trapping the player inside of a nearby rock

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#295]
When travelling from the train tunnel in W.D. Residentials to the train tunnel in W.D. Underground using the entrance, the player may spawn inside of a rock to the right when facing the rock blockage from the W.D. Residentials side.

This bug can be avoided by not travelling to W.D. Underground from W.D. Residentials using the entrance.

This bug was observed while playing the game on a computer.

The version on which this bug was observed is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/a4e3d696-4f6d-40d1-8b0f-eba31bfa6e85

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/e7372e76ff6124e7e8ad9f2a33fc95b5a88584ae
