### ISSUE TITLE
When using a Chainsaw to hit a target continuously, some hits are ignored

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#296]
Holding down the attack button with a Chainsaw equipped and attacking a target that can survive multiple hits has a chance to not damage the target from the second hit onwards. This bug is particularly obvious if the player also has Melee Fury equipped, but still occurs without it.

This bug can be avoided by tapping the attack button at a slower rate than the attack speed; DPS also improves significantly while doing this.

This bug was observed while playing the game on a computer.

The version on which this bug was observed is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/b54ce2a7-8816-400d-9a48-8f98e1c972a0

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/b67e0e30-0e29-4830-9d00-76937b91cdf3

**Comment by Leroy8888** [comment]
Probably related to this old issue https://trello.com/c/C1Mw0P3O/16088-the-faster-attack-speed-caused-by-melee-fury-doesnt-match-the-animation-playtime-of-melee-attacks
