### ISSUE TITLE
Voodoo doll bug

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#297]
The voodoo doll will force the player into different directions (https://gyazo.com/e6920f3a9da181afb6ab9b3f2f8453ff).

When equiped, the doll will appear without any body parts and slowly drag the player towards the body parts. As they likely spawn somewhere off the map and make their way to the doll. If the player holds the doll out for awhile, the body parts will reattach themselves.

This seems to be caused by the ragdoll of the voodoo doll. When the body parts attach themselves again it also adds additional weight to the player, making movement more difficult.

**Comment by MXKhronos** [comment]
This is intended.

**Comment by Leroy8888** [comment]
If this is indeed intended to be as it functions in dev branch, then the discription should be changed in way where it mentions that the doll influences the player's movement.

Even with said change it would still be very likely that a lot of people will find the behaviour of the doll on equip unintended and as result report it or consider it a bug. Which could potentially lead to a lot of duplicates of reports.
