### ISSUE TITLE
Players are unable to collect Robert's beanie after data resetting

### ISSUE THREAD

**Issue by ghost** [HelixNebulaStudio/RiseOfTheDead#3]
This softlocks the player during ‘'Missing in action’'

This issue occurs because the player has already collected the beanie collectible prior to resetting their data. This causes the beanie to appear and instantly disappear once players tries to interact with it after.

https://trello.com/c/676AFpvO/16352-players-are-unable-to-collect-roberts-beanie-after-data-reseting

**Comment by MXKhronos** [comment]
There's a long rewrite in the background for systems that handle missions and cutscenes. This will be fixed soon.

**Comment by MXKhronos** [comment]
Fixed
