### ISSUE TITLE
Weapon's ammo customization in dev branch

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#30]
Currently in dev branch you can customize bullet parts in weapons. This is one of those things that players have wanted. Unfortunately, some weapon's bullets require a texture for the colour to change. 

Of course fired bolts and empty casings are in their original colours.

Could this unintentional feature be fleshed out into a fully-fledged customization option or will it be patched out? 

While talking about this "new feature" with other players they have brought up that they would like to be able to change the tracer colour.

**Comment by MXKhronos** [comment]
Now customizing bullet will remove the base texture. But that's the extent for customization since then ejected bullets uses a external preset model.

Coloring tracers are still currently reserved for special mods.

**Comment by MXKhronos** [comment]
Fixed
