### ISSUE TITLE
The first bandit in the Bandit Outpost raid does not always attack the player

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#300]
At the start of the Bandit Outpost raid, a bandit will spawn near the front of the warehouse on the ground floor. This bandit will not attack the player immediately if bandits are neutral to the player. The behaviour of this bandit when bandits are hostile to the player has not been tested.

This bug can be avoided by not entering the Bandit Outpost raid.

This bug was encountered while playing the game on a computer.

The version on which this bug was encountered is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/cfd2c54d-ba5a-4a14-b6ba-dfc2c7a941ee

**Comment by zxcvbgfrtyui** [comment]
I would like to point out that the bandit in question is marked by Threat Sense, has a weapon equipped and moves away from the player when approached, but uses the passive animations (not holding the gun to fire).

**Comment by Leroy8888** [comment]
As far as I can tell, this issue already seem to fixed in dev branch. So I'll close it for that reason.
