### ISSUE TITLE
Invisible object on the stairs to the basement of the shop building in the Community Safehouse

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#305]
When walking down the stairs to the basement, the player will briefly crouch halfway through the stairs. When walking up the stairs from the basement, the player will crouch halfway through the stairs and will be prevented from ascending any further. This can be resolved by jumping while moving up the stairs.

This bug can be avoided by sliding down the stairs and jumping up the stairs.

This bug was encountered while playing the game on a computer.

This version on which this bug was encountered is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/cb7b1263-c75b-4a27-b838-479e1669b3b0

**Comment by MXKhronos** [comment]
Fixed.
