### ISSUE TITLE
Invisible barrier blocking the grate door at the end of the Genesis co-op

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#306]
After opening the grate door at the end of the Genesis co-op, the player will be unable to walk through the door due to an invisible barrier.

This bug can be avoided by jumping over the invisible barrier.

This bug was encountered while playing the game on a computer.

The version on which this bug was encountered is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/e71024c9-cb43-4764-8e51-9eba49dc530e

**Comment by MXKhronos** [comment]
Fixed.
