### ISSUE TITLE
Robert does not wait to attack the player and can become stuck on barrels under certain circumstances

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#308]
Before the 2.0 update, Robert would wait for approximately 5 seconds before attempting to attack the player after the player opens the door to his room and after each successful hit. Robert now rushes towards the player immediately after the door is opened and does not wait after successfully hitting a player, but does not attack players if they are ragdolled due to his attacks. Additionally, Robert can be 'cheesed' by standing on barrels near the fire. While not reliable, Robert will often 'hug' a nearby barrel while standing on a burning puddle, causing him to take a high amount of damage while keeping the player relatively safe from Robert and the fire.

These bugs can be avoided by not playing the Genesis co-op.

These bugs were encountered while playing the game on a computer.

The version on which these bugs were encountered is 2.0.7.17.

[https://youtu.be/LLlOPn9tIXA](https://youtu.be/LLlOPn9tIXA)

**Comment by MXKhronos** [comment]
Added delay to response to players entering the boss room.
