### ISSUE TITLE
Nekros trench coat doesnt visually have a hoodie

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#309]
there is 3 variation  of the coat which is normal, hoodie or pumpkin. 
but the hoodie variation doesnt actually have a hoodie and its just a normal variation of the coat

![Screenshot (244)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/2c83cb76-e2ca-4b8a-b69e-919c4f5e95da)

**Comment by MrPigZ** [comment]
The hoodie version removes the collar and adds a hood which is resting on player's back.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/835cfc1f-dee7-47b4-b61c-f767d670bc25)
The workbench model does not display the hood.
