### ISSUE TITLE
Npc items aren't connected to new hands

### ISSUE THREAD

**Issue by Speedycar777** [HelixNebulaStudio/RiseOfTheDead#31]
The items that are held by certain Npcs are not connected to the new hand model

**Comment by MXKhronos** [comment]
Need details

**Comment by Speedycar777** [comment]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/8cedc5d3-c43f-4b87-90a1-df2a088278a3)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/797bf10b-313b-4b91-bb9c-6a4799009a29)

**Comment by MXKhronos** [comment]
Fixed
