### ISSUE TITLE
Robert has a right hand during the Genesis co-op

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#310]
Robert's right hand was supposedly severed and stolen during "The Investigation", but in the Genesis co-op, he can be seen with a right hand.

This bug can be avoided by not reaching Robert's room in the Genesis co-op.

This bug was encountered while playing the game on a computer.

The version on which this bug was encountered is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/b7904ada-0d31-4b30-b290-de60268fbfdf

**Comment by MrPigZ** [comment]
"Are you questioning nekron's capabilities?" - some biox scientist probably
