### ISSUE TITLE
some sleeves seems to disappear when wearing or set a vanity of leather gloves

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#312]
![Screenshot (245)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/8a92785a-b4a0-4879-a931-c6676be02f2a)
![Screenshot (246)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/16243806-1c69-467e-9b78-734cf663c85e)
![Screenshot (247)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/6e0d8615-da87-4ffd-a61e-cd2492a083cc)

**Comment by MXKhronos** [comment]
This is intended based on your clothing order.
