### ISSUE TITLE
`The Investigation` bugs

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#315]
A few issues are present in the mission. They aren't game breaking, but I will note them here since they are quite noticable.

### Noticable

Robert does not play any animation when he rips off Joseph's arm https://gyazo.com/76b9e7cb7a2df6699438187630d8ecf1

Ocassionally, Robert will fail to properly hide himself after he flees the scene. Normally, Robert teleports up to a brick above the scene out of bounds. However he will sometimes fall back down and go through the hole which can lead to him being visible after Zark left.
![Schermopname (12576)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/8418ad2c-9c9b-4e26-b278-27d757a426ba)
https://youtu.be/Farv-Ks0ARs?si=0KKjwOc2e_3pqqS9&t=131
Nate will also start shooting Robert when he gets too close.

If the conditions are met to start `End of The Line` the player can talk to Joseph again while he's bleeding out to start the mission. This seems to occur randomly. Unsure what exactly causes it. https://youtu.be/Farv-Ks0ARs?si=EPDBb1Feeyqb9IFq&t=153

### Minor issues

Using a weapon to deal sufficient damage with frostbite will mess up Robert's speed. The slow depends on the amount of stacks. A full stack will fully prevent Robert's movement for the duration of the mission. https://gyazo.com/acb4693ef21dd9009bce01f643fe3280

If the player attempts to dodge Robert's attack, Robert will freeze in place at the end of the charge until the player touches him. It is important to note that Robert only attempts to charge the player in a straight line once, which can be dodged with relative ease.

**Comment by MXKhronos** [comment]
Fixed up the moderate issues, the reminding ones will need some diagnosing and is negligible.
