### ISSUE TITLE
Zombie Hair Blocking Headshot Damage

### ISSUE THREAD

**Issue by Speedycar777** [HelixNebulaStudio/RiseOfTheDead#32]
The zombie hair isn't connected to the head hitbox counting it as a normal body shot.

**Comment by Leroy8888** [comment]
Reoccuring issue, card related to: https://trello.com/c/eiBLYgTD/16240-roblox-clothing-items-accessories-and-ingame-holstered-melee-weapons-block-hitscan-weapon-attacks

**Comment by JakobCh** [comment]
Feel like they shouldn't have collision on them at all since they can be different sizes.

**Comment by MXKhronos** [comment]
Disabled npc accessories hitscan detection.
