### ISSUE TITLE
Hector Shot doesn't move (does not occur on all servers)

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#322]
Hector Shot does not move from his starting location. He will turn to face players, but stay where he is.

This bug can be avoided by joining another server.

This bug was encountered while playing the game on a computer.

The version on which this bug was encountered is 2.0.7.17.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/5fc16e2b-f73c-46d5-ba27-71b909a7514a

**Comment by MXKhronos** [comment]
Should be fixed, related to https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/278
