### ISSUE TITLE
Killer Hues isn't in the mission tab menu

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#328]
Unless this mission is supposed to be a secret one.

**Comment by MXKhronos** [comment]
`The Killer Hues` should appear if you have Lydia in your safehome and is level 5.

**Comment by Leroy8888** [comment]
You can start the mission when the conditions are met, but there's no entry for it on the mission board. You would only discover that the mission is a thing if the player at one point went to your safehome and saw a ''!'' above Lydia's head.

For clarification on the mission menu, I meant the menu you view when you open the mission log. Where you can see the progression of your missions and upcoming quests.

**Comment by MXKhronos** [comment]
Could be a case where the mission isn't added until talking to Lydia, made some changes for that.

**Comment by Leroy8888** [comment]
I did complete the mission, but I don't see it in the mission menu.

Is this change pushed to main or dev branch?

**Comment by MXKhronos** [comment]
I tried loading your save and it appears under side missions. Let me know if you see it.

**Comment by Leroy8888** [comment]
Took a few rejoins but it appeared now.
