### ISSUE TITLE
Vein of Nekron Not taking any damage

### ISSUE THREAD

**Issue by Speedycar777** [HelixNebulaStudio/RiseOfTheDead#33]
After testing every type of damage or way to damage the vein not a single thing damaged it
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/b328890c-a0c8-49b0-8bb5-ac1adccf21e4)

**Comment by Leroy8888** [comment]
This might correlate to the same issue tire armor currently experiences

**Comment by MXKhronos** [comment]
Fixed
