### ISSUE TITLE
People cannot enter tombs during Vindictive treasure I

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#331]
Same issue as before but now in a different form with this log
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/1bb5b06d-02b4-40ca-a4b7-5b6201764ff6)
and this one
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/aa61904b-7215-4d41-aa00-57af5941b18e)

From #245

**Comment by Leroy8888** [comment]
#251

**Comment by MXKhronos** [comment]
Finally figured out the actual cause, thanks!
