### ISSUE TITLE
Event pass completionist titles

### ISSUE THREAD

**Issue by MrGarrettFerret** [HelixNebulaStudio/RiseOfTheDead#332]
I saw that the event pass titles now no longer display the player's level in that event pass on them. To keep it short, I and likely many others are **not** happy about this change and wish to see it reverted. Many people including myself have sunk many, many hours into these events and to see all of that time wasted due a seemingly arbitrary decision is not good. While at the end of the day it may be just a number next to a title I don't use, it represents the hundreds of hours I put into the event and I do not like how all of my time was just wasted due to this change. It also does not help that the unlockables (now skin-permanents) I got from grinding this event now cannot be freely traded either.

**Comment by MXKhronos** [comment]
This was not intentional and will be added back. It was mistakenly removed because I commented out previous event passes configurations which caused the script to think it does not exist and failed to retrieve your levels.
