### ISSUE TITLE
Lydia doesn't have any mini quests to level her up.

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#339]
When people unlocked Lydia as safehome survivors the mission doesn't appear. This normally would occur at level 5, which can be done by doing a few tasks for Lydia such as providing purple lemons.

Unfortunately, for a lot of people these tasks do not seem to appear which prevent them from leveling up Lydia.

This makes it impossible to unlock the mission.

Currently unsure what causes it and will need to run some tests to pinpoint a cause.

**Comment by MXKhronos** [comment]
I'm not able to replicate anything related

**Comment by MXKhronos** [comment]
I've added some extra logs to diagnose this.

**Comment by Leroy8888** [comment]
Alright as it seems the issue is not present in dev branch anymore. I've had a few people test in there and it did seem like they were able to continue. Not sure which change caused that.

A lot of people seem to experience this in the main version of the game though. Possibly the entire playerbase, although I am not too sure on that. People who've done the mission did level up Lydia way before 2.1.0 launched, so they were able to bypass the issue.

This is also unrelated to the issue, but I was wondering if we could get a command to load saves of other players. I am aware this could be abused and can also be used to invade privacy or things players would like to keep for themselves (whatever it may be) but it would be a huge tool to replicate issues reported to testers. 

Most reports tend to be very vague in their discription, so just having the option to load a save as it is and try the issue for yourself could significantly speed it up while also possibly giving more insight on the issue.

**Comment by MXKhronos** [comment]
Okay, I figured out what's wrong from the new logs. After acquiring `Lydia` from `Another Survivor`, the cutscene where the npc should move towards their post bugged and failed to level her up to level 1.
