### ISSUE TITLE
Zombies get stuck in fission bay at every wave

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#340]
Without explosive weapons you cannot clear waves. At every water spawn zombies get stuck and stay under the water indefinitely. Add high sea hazard and now you need other players to sacrifice their lifes to kill the zombies.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/ce327649-c141-4295-bb96-941bc2f9b0d3)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/19611def-2a3d-4d9d-b617-9e54efd34091)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/a2f9861e-cd00-4790-90ca-69d90a05dfba)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/4257bf9f-536a-48d1-896e-c490521b5bb2)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/108bf59d-73ef-4e34-b035-9999beb44b99)

**Comment by mega00913** [comment]
I think the main issue here is that the 2.0 zombies do not swim like the 1.0 ones do.

The FB map walls are lined with truss/wedge clips, which are designed for zombies (swimming on the water surface) to easily climb onto the main platform. It is not intended for zombies that sink below the water surface (as it is previously not possible for them to do so), which I suspect is the reason for the issue.

Could you check if zombies in W.D Harbor are able to swim at all or are do they "sink" / "walk" underwater? Would like to know if this is just limited to FB, thanks!

**Comment by MrPigZ** [comment]
Zombies sinks and walk under the water in FB and in Harbor.

Though one thing that I dont understand is that how I did not experiene this during 3 different FB runs in version 2.0.
