### ISSUE TITLE
Warning before using a survivor poster if the survivor is already present

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#345]
If the survivor on the poster is already in the player's safehome they'll receive a warning that using the poster does not grant an additional survivor but rather a random safehome survivor

**Comment by MXKhronos** [comment]
The response when selecting a wanted poster of npc who's already in your safehome would not let you put them up. But I'll change it to not show up at all to clear up the amount of options shown.
