### ISSUE TITLE
The billies from the rooftops are sometimes unkillable.

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#346]
The billies cannot be damage because the damage from the players are not registering to the billies.

https://youtu.be/KSKl73yZp_w

**Comment by MXKhronos** [comment]
Has anyone experienced this elsewhere other than Rooftops?

**Comment by rafaderren** [comment]
got this issue before, tried shooting them but they didnt get damaged

**Comment by MXKhronos** [comment]
Reopen this if the fix attempt didn't fix this issue since I can't seem to replicate this.

**Comment by Rookie21333** [comment]
> Reopen this if the fix attempt didn't fix this issue since I can't seem to replicate this.

its still occurs but on early waves they can be damaged and killed but when it goes in wave 15 they cant be damaged anymore and its also wave 15 shown in the video

**Comment by Rookie21333** [comment]
Welp it still occurs randomly in a waves, I don't know what to say about this one

**Comment by Rookie21333** [comment]
it still occurs, they still can't be damaged sometimes the only way to kill them was to make them fell off the building

**Comment by MXKhronos** [comment]
> it still occurs, they still can't be damaged sometimes the only way to kill them was to make them fell off the building

Are you on that server right now?
