### ISSUE TITLE
Ticks Zombies do not damage resupply radios or generators in Survivals and instead deal damage to other zombies

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#348]
Ticks Zombies will start their explosion countdown once in range of a resupply radio or generator and explode as usual, but these explosions deal no damage to resupply radios or generators. Instead, these explosions will deal flat damage to any other zombie in range, killing them in extreme cases.

This bug can be avoided by not allowing Ticks Zombies to explode within range of a resupply radio or generator.

This bug was observed while playing the game on a computer.

The version on which this bug was encountered is 2.1.0.16.

(video may not work yet)
[https://youtu.be/Ga95THlWb3k](https://youtu.be/Ga95THlWb3k)
All damage to the resupply radio in this video that is at least 15 (what a Ticks zombie should do at least) comes from not resetting the radio, which is 200 per second.

[https://youtu.be/pu9auKTmB9c](https://youtu.be/pu9auKTmB9c)

**Comment by Rookie21333** [comment]
Ticks zombies damaging other zombies is intended and the generator and resupply radio are already in the issue.

**Comment by zxcvbgfrtyui** [comment]
Just realised that this is a duplicate of another issue that's open now (#344), probably close it
