### ISSUE TITLE
Portable Auto turret Blueprint wont craft

### ISSUE THREAD

**Issue by Speedycar777** [HelixNebulaStudio/RiseOfTheDead#35]
Finished the mission and had the materials to craft but it constantly said not unlocked
Dev console doesn't have any errors.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/d297f196-4956-4788-89d7-510d45572c2d)

**Comment by MXKhronos** [comment]
Fixed
