### ISSUE TITLE
A few mods completely break guns

### ISSUE THREAD

**Issue by Speedycar777** [HelixNebulaStudio/RiseOfTheDead#36]
It looks like both smg and rifle damage calibres and both crit mods break guns not being able to equip or customize the weapon
Error while attempting to customize
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/a54f2ff7-b44f-40b5-8e4c-510aa153dbb7)|
Error while trying to equip
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/271b9fe9-3249-4d4a-9670-8e38211984e4)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/38660a76-3af6-4712-8e35-89287e184ed2)
Damage Rev
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/2a9ff475-af55-4d60-bab5-df6be9d07a39)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/6b7435a7-9b04-4bbb-9aec-ad20b567bc28)
Attempting to customize weapon with broken mod
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/58f62b51-8348-45fd-9506-a4fb4c0f3eb7)

**Comment by Speedycar777** [comment]
yep just was finding the current ones that completely brick the guns

**Comment by JakobCh** [comment]
this also causes problems with armors that have armor mods equipped

**Comment by MXKhronos** [comment]
Fixed by clamping to minimal mod level to 0.
