### ISSUE TITLE
Throwable melee weapons seem to deal 150% of the damage as a minimum

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#360]
Pointed melee weapons deal at least 150% of the listed damage when thrown. This is 3 times higher than the half damage that is claimed in the weapon descriptions.

This bug can be avoided by not throwing pointed melee weapons.

This bug was observed while playing the game on a computer.

The version on which this bug was observed is 2.1.4.16.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/4af48f02-0444-4c20-961f-d3ba3efe7b42

**Comment by Leroy8888** [comment]
https://trello.com/c/CbL8Cma6/16202-change-throwable-damage-from-melee-weapon-to-2x-instead-of-050x Desc doesn't seem to have been adjusted
