### ISSUE TITLE
Possible bug with Wanted Poster drops

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#361]
When Wanted Posters are dropped in W.D. Residentials, it seems that the target is almost always Rafael (over 10 times) and almost never Scarlett (just once). Similarly, for W.D. Harbor, I have only ever obtained Jackie posters, even though there are (presumably) 2 that can be sourced from W.D. Harbor.

**Comment by MXKhronos** [comment]
They have different drop rates.
Check drop tables: `RegionDrop:Mall Street`, `RegionDrop:Residential Street`, `RegionDrop:Harbor Crash Site`.

**Comment by zxcvbgfrtyui** [comment]
![Roblox 9_07_2024 2_07_45 AM](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/057f1ed4-6a5c-4c9d-8f29-5d21b232bf3d)
The drop rates of the posters are identical when using commands. This may be due to an existing bug where (presumably) for similar sources (like different days of extreme bosses), the first source will be repeated for every source.

**Comment by MXKhronos** [comment]
Apparently the `/item` cmd isn't accounting the item values which contains specific wanted posters it drop.
