### ISSUE TITLE
No killbox for zombies on Rooftops

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#363]
In the Rooftops map zombies don't die when they fall off the tower
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/66e129a9-db33-4daf-873c-10433e7efa36)

**Comment by MXKhronos** [comment]
Related. https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/346
