### ISSUE TITLE
Fumes spawning in survival

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#366]
Fumes has a tendency to spawn in survival maps and then remain at its spawn point since it's coded to stand still.

This makes it difficult to hit Fumes without the proper tools like explosive or ricochet and can cause a softlock in survival.

Example on rooftops: 
![Schermopname (12635)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/3b2df633-f771-410b-8561-ec45be525e10)

![Schermopname (12672)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/2b2bee06-c9bc-4ba1-ab6b-d00f26aa0da1)

**Comment by MXKhronos** [comment]
This should give Fumes time to walk out of spawn points before able to start channeling `Fumes Cloud`.
