### ISSUE TITLE
Zombies repeatedly walk into players and push them, even if they're close enough to deal significant damage

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#368]
Once alerted by a player, zombies will move towards players to attack them. However, zombies seem to attempt to move directly onto the spot where a player is standing, causing players to be pushed back if they are still standing there due to the zombies becoming impossible to push as of the 2.0 update. Zombies will additionally continue to attempt to stand on the player's location, causing the player to be pushed further and further back, then to the side if the player is pushed into a wall. This behaviour is particularly disruptive if the player is standing in front of a high place (such as the part of the monorail in Sector D just before the carriage drops down), as players may be pushed off if they are standing too close to the edge.

This behaviour can be avoided by killing zombies before they touch players.

This behaviour was observed while playing the game on a computer.

The version on which this behaviour was observed is 2.1.4.16.

**Comment by MXKhronos** [comment]
This is a intended change.
