### ISSUE TITLE
Growlers dont take frontal melee attacks after it got hit

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#375]
the growlers cannot be damaged after i attacked it with melee and still cant be damaged after its Nekron exoskeleton was removed.
I don't know if other melees cause the same but i was using chainsaw at them

Ranged weapons normally works on growlers.

**Comment by Leroy8888** [comment]
Can confirm, the hit registration on growlers seems a bit unusual at times. Sometimes to passes through the exoskeletons and hits the main body, at other times it only hits the skeletons and there are also instances where the collider doesn't damage the entity at all.

**Comment by GregTheBestest** [comment]
Had same issue just today.
