### ISSUE TITLE
Incendiary stacks on entities with multiple parts

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#379]
The incendiary DoT stack will keep on stacking on the part is was first applied on, regardless if the player hits the same part.

For example, when the nose of the bandit heli is shot twice the it will stack 2 incendiary stacks, but if the player decides to aim and hit the body next it will instead apply more stacks to the nose part of the heli and won't apply any stacks to the body.

**Comment by zxcvbgfrtyui** [comment]
If this is a bug, I'd say that this is pretty significant. Being able to damage multiple parts with Incendiary at the same time would lead to incredible % damage, especially with the duration maxed. On the other hand, Incendiary stacking on the same part regardless of the part hit makes strategies like shooting Zomborg Prime's core once with Incendiary, then spraying Incendiary bullets all over Zomborg Prime highly effective.
