### ISSUE TITLE
The PaT stops shooting entities which are under the effect of toxic barrage

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#381]
Most notable during Zenith bosses or extreme bosses

**Comment by MXKhronos** [comment]
What's your PAT configurations?

**Comment by Leroy8888** [comment]
The configurations are as follows;

Distance priority: Closest

Health priority: Highest

Speed priority: Fastest

Crowd firing mode: Disabled

Cap fire rate: Uncapped

Charge Focus Disabled

Toxic Barrage Mode: Disabled (having it enabled does not change anything regarding the issue)

Frostbite mode: Disabled

Debuff Only: Disabled

Use costum Hitlist: Disabled
**if** enabled:
Targets Dr. Sinister and Bosses.

**Comment by MXKhronos** [comment]
`Debuff Only` mode apparents to be the issue, it was stuck on enabled in code. And another bug where it doesn't recompute target after debuffing them.
