### ISSUE TITLE
Mariner 590 idle animation doesn't look right

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#383]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/138b5cd3-b106-43f3-a434-83c89dfd9318)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/53db357f-d027-4488-bb77-4024e21a12ea)

**Comment by MXKhronos** [comment]
Fixed, left arm was suppose to be relaxed.
