### ISSUE TITLE
Navigation additions for workbench customization options

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#385]
Since the addition of Lydia's task and the many custom colors we can obtain along with the options we already had, the list becomes quite long.

It's also fairly difficult to tell which of the custom colors are unlocked. You can't just simply hover over a color and see the hex color code.  It's especially difficult with custom colors from the post rewards, as there wouldn't be some menu to display which color has been unlocked already.

To make it a bit easier to navigate the workbench I would like to suggest a search function at the top of the costumization menu. In this menu **tags** can be used. Tags can be used to quickly navigate to specific collections of costumization options such as Lydia's colors, offline textures or other options. When doing so, the menu would hide everything that is not in the tag. The player could also choose to fill in the name of a color such as #D20103 which would directly apply the color on to the weapon part. When this would be used along with the tag it would instead take the player to the color itself in the menu so that the player can choose between colors that look alike.

Another suggestion would be to allow players to view the names of costumization options by hovering over them. This could be used for the search bar and could also help to sort out random colors from the current pass post rewards.

Lastly, I would suggest to make Lydia be able to scavenge a random color from the hex color code which aren't already present in the menu you can pick from. This option _could_ be locked until lydia scavanged all the colors in the menu. The cost and time would remain the same.

It would be nice to have a way after the event pass to gather colors that aren't in Lydia's options. As it is very unlikely that anyone would attempt to grind 23.7 billion levels on the pass just to have a _chance_ to unlock all of the colors. Alternatively #265 could be used for this purpose.

**Comment by GregTheBestest** [comment]
I liked the first half of the message. 2nd half with Lydia being able to collect random color seems strange to me. As far as I know there are 128 colors in Roblox palette, which is used in Lydia's mission. Taking in account the a line of colors in workbench customization is 9 colors, it would take 14 full lines of colors. I believe with this amount of colors, the entire customization window will be covered in Lydia's colors every time unless you close the window. Additionally it would be quite hard to navigate through all these colors.

**Comment by Leroy8888** [comment]
The 2nd half of the message assumes the max amount of possibilities for the colors is the same as those of hex colors, which would be 16,777,215.

When I viewed Lydia's color palette during testing, I assumed it would be the max amount of colors available both from Lydia and the event pass. As it turns out, the event pass introduces colors that cannot be obtained through Lydia, though I am unsure whether this is the same amount as the possibilities of hex colors. 

Perhaps granting the player a way to unlock them all might be a bit extreme indeed. So if it would indeed be all the possibilities from hex, instead it can be applied by an NPC who would sort the colors into basic or ask for a specific hex color code.
