### ISSUE TITLE
Flamethrower projectile hitreg without Flame Burst is highly unreliable

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#389]
When firing a flamethrower without Flame Burst at a horde of zombies, the flame projectile has a high chance (maybe 30-50%) of failing to ignite zombies in its path, often leaving multiple zombies in its path unharmed. Once applied to a surface, the fire reliably sets zombies that touch it on fire (so it works properly when put on surfaces).

This bug can be avoided by applying fire to a surface and leading the zombies through the fire instead of attempting to directly apply it to zombies.

This bug was observed while playing the game on a computer.

The version on which this bug was observed is 2.1.4.16.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/df29f3ad-ddeb-4fc7-a228-bcdf05635b6c

**Comment by choppygraph** [comment]
I was in my private server, first doing Sector D and then in the residentials trying to kill zombies with the flamethrower, I got the same result.
In sector D, nothing died from the flames. I placed multiple flames in nearly every doorway and not a single zombie took damage, tried the same thing in the residentials and nothing is taking damage from the flamethrower.

**Comment by MXKhronos** [comment]
Increased projectile hitbox.
