### ISSUE TITLE
Player can tweak melee weapons

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#392]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/e55b466c-d04b-4149-b320-ed08cb754173)
Megatron was tweaking his rec21 and somehow his chainsaw got a tweak.
"Man, I dunno how this could happen fr." -Megatron_2009

**Comment by Leroy8888** [comment]
Appears to be only a visual issue

**Comment by MrPigZ** [comment]
I can't reproduce this issue.
