### ISSUE TITLE
Gift shop change

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#395]
I've noticed, along with some other members, that the gift shop contents got changed to being exclusively for premium accounts.

While this wouldn't be such an issue if this occured right at launch, it is now. Since there are quite some players who have already converted a lot of items into tokens which they now no longer can use.

Some way to compensate these players for the efforts would be nice and I would like to suggest that players can still use the tokens to claim rewards from the gift shop, but can no longer get anymore tokens without premium.

Another way would be to let players roll post rewards of the pass with the tokens, but this does divert from the initial point of grinding tokens.

**Comment by MXKhronos** [comment]
It was designed and labelled as for premium at launch, but there was a bug where non-premiums could unlock items from the gift shop. I'll just allow non-premium to use the gift shop.
