### ISSUE TITLE
Mission pass books arent dropping

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#398]
Doing actions that would normally give them wont give mission pass books

**Comment by MXKhronos** [comment]
The drop cooldown has increased depending on the amount of `mpbook` you already obtained with the most being up to 5.5 hours.

**Comment by Rookie21333** [comment]
> The drop cooldown has increased depending on the amount of `mpbook` you already obtained with the most being up to 5.5 hours.

is the cooldown increased? because when i get 1 book by joining the game, i never got more than 1 book like i used to before 2.1.5 update
