### ISSUE TITLE
/spawnitem can only spawn some items

### ISSUE THREAD

**Issue by JakobCh** [HelixNebulaStudio/RiseOfTheDead#40]
There seems to be some items that don't spawn with the /spawnitem command.
There also doesn't seem to be any feedback if you type the command wrong, example: "/spawnitem egg e".
It would also be nice if it could provide the same functionality as the /give command and suggest item ids.

Commands that work:
/spawnitem p250
/spawnitem sectorfcrate
/spawnitem rec21
/spawnitem cannedbeans
/spawnitem molotov
/spawnitem ladder
/spawnitem glass

Commands that don't work:
/spawnitem gastank
/spawnitem igniter
/spawnitem gears
/spawnitem militaryboots
/spawnitem divinggoggles
/spawnitem cloth
/spawnitem metal

**Comment by MXKhronos** [comment]
Fixed
