### ISSUE TITLE
side missions come back and give rewards

### ISSUE THREAD

**Issue by Exonouss** [HelixNebulaStudio/RiseOfTheDead#406]
basically i completed this side quest years ago and now i have to redo it, and i also got rewards from it, im very sure ive done it before cuz i had 24/24 missions
![Uploading image_2024-06-02_094647588.png…]()

**Comment by Exonouss** [comment]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171178292/1455605f-9a22-425c-9182-06e25a993016)

**Comment by Exonouss** [comment]
the first image
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171178292/3a067fc7-7dae-4487-9f5a-f72439a179f9)

**Comment by MXKhronos** [comment]
Related to another bug about skipping board missions removing the wrong mission.
