### ISSUE TITLE
Camera stays locked in mission Medical Breakthough when bandit comes to investigate the lab

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#407]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/724e424d-6c1b-4b6c-a66b-575456bf65eb)

Can be fixed by toggling on and off free cam but new player doon't know about it.

**Comment by Leroy8888** [comment]
Won't re open this since I assume this is a general fix for the issue, but this occurs in all missions where the camera locks in a specific place.

Such as `The Prisoner`
