### ISSUE TITLE
Player can get multiple blueprint pieces that are related to the mission Belly of the Beast

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#409]
Will clog players inventory forever. Player can get extra pieces from opening multiple chest before completing the quest. Collecting 1 piece inside of vexeron, leaving and coming back to cather more.

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/85422c43cef1c048791140b70bff8b7c7846b14c
