### ISSUE TITLE
Tick Snare Trap

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#41]
ItemId: `ticksnaretrap`

A snare trap that leashes a Tick that runs over it. Killing the leashed Tick resets the trap. It can leash up to 10 times.

Final tests and balancing.

**Comment by Leroy8888** [comment]
A single Tick can get caught in multiple snares. Which will cause it be be flung all over the place and possible transfer it's momentum to neatby entities if they interact.

**Comment by Leroy8888** [comment]
The snares also stay connected to the body parts of the Tick until they despawn. Might no be intentional, but it also makes the trap slightly worse.

**Comment by MXKhronos** [comment]
Trap should reset as soon as the Tick dies and no longer gets snared multiple times.

**Comment by JakobCh** [comment]
Just tried this out playing sector F.
Caught my first tick and shot at it with my Rusty 48 and it didn't seem to take any damage.
Shoot at it a couple more times and then I noticed that I couldn't switch weapons.
A minute or so later I get disconnected from the server.

Tried it again and this time the server came back after a couple of seconds. I think I fired less shots at the tick this time.

I think this might have something to do with the fact that shotguns seem to apply a lot of physics force to whatever they hit.

**Comment by MXKhronos** [comment]
> Just tried this out playing sector F. Caught my first tick and shot at it with my Rusty 48 and it didn't seem to take any damage. Shoot at it a couple more times and then I noticed that I couldn't switch weapons. A minute or so later I get disconnected from the server.
> 
> Tried it again and this time the server came back after a couple of seconds. I think I fired less shots at the tick this time.
> 
> I think this might have something to do with the fact that shotguns seem to apply a lot of physics force to whatever they hit.

Could be related. https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/c85cbc3d0e0358c9c3dc137c3a70105752e07bf2
