### ISSUE TITLE
MPBooks don't drop after obtaining the first book

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#418]
Let me make the issue #398 clear.

Mp books drops faster if you have few books obtained and drops slow if you obtained a lot.

But there's a problem, the books don't drop anymore after obtaining one book no matter how many stuff I need to do to obtain books it doesn't work for few hours.

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/398 Duplicate

**Comment by Leroy8888** [comment]
I hate to reopen issues like these and constantly question the mindset behind these changes but, what was it for this particular change?

The MPbooks as they functioned allowed players, even endgame players, to grind for the books during the event, which actually caused the game the receive a steady amount of player for a longer period of time as it gave them something more to aim for. Unlike a regular update, where it would dwindle back to the former player count in a few days.

Players which wanted to spend extra time in the game and grind for the pass could. If they want to sink in a considerable amount of time then In my opinion I would let them be. It's not like the books are obtained in a illegitimate way.

This change kinda supports the ''playstyle'' of logging on every 6 - 7 hours. Do missions and get a book or 2 then log off and repeat. It doubles down on the less fun to do aspect of doing the same tasks every so now and then and makes it feel like a chore as missing out on them limits the possibility to receive rare loot from post rewards. With the other system, players could do their regular activities and gain a steady amount of points if they decided to stick around.

**Comment by MXKhronos** [comment]
The current problem is I need to reduce the rate the amount of gold drained from the event pass gold pool from people grinding `mpbook`. It's only if you've obtained 200+ mpbooks already which would supposedly mean you've completed the event pass, if you hadn't obtained 200+ mpbooks, you would still get a book at the same rate as before for you to complete the pass.

I'm still thinking of ways to solve this while I work on other issues.
