### ISSUE TITLE
Threat sense does not highlight enemies on mobile devices

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#420]
No background on this one yet unfortunately.

A comparable issue has been opened on trello quite some time back and it seems to be archived (https://trello.com/c/Idu4N34F/16074-threat-sense-doesnt-work-on-mobile). The player did not configure any options that would alter the gameplay and also did not switch between apps.

If it helps, the device uses android.

**Comment by MrGarrettFerret** [comment]
Possibly related to https://devforum.roblox.com/t/highlights-dont-render-when-switching-between-apps-on-mobile-devices/2947267
