### ISSUE TITLE
Zombie kills sometimes not registering SEVERE ISSUE!!! "BUG"

### ISSUE THREAD

**Issue by starlintons** [HelixNebulaStudio/RiseOfTheDead#421]
Occasionally killing a zombie does not register and does not give any reward/loot. 

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171533555/9039c7d6-5b23-4829-802a-bb06d0c3a15b

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/506190ecba6208ca79042425c6243a2d1a14ee62
