### ISSUE TITLE
Mysterious Engineer's Belly of the Beast dialog doesn't appear despite having Blueprint Piece

### ISSUE THREAD

**Issue by Geocraftery** [HelixNebulaStudio/RiseOfTheDead#422]
Opening the SunkenShip Chest outside the Co-op and re-entering already having a Blueprint Piece causes the dialog for the mission never to appear.

**Comment by MXKhronos** [comment]
@Geocraftery Are you experiencing this in your save? If so what's your userId?

**Comment by Geocraftery** [comment]
Yes, it's on my save. My userId is 755409913.

**Comment by Nugget-Sk** [comment]
I am experiencing the same issue

**Comment by MrPigZ** [comment]
What are the actual requirements to start this mission other than the blueprint piece?

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/85422c43cef1c048791140b70bff8b7c7846b14c

**Comment by MrPigZ** [comment]
I am having this issue in dev branch. Is the fix made added there?

**Comment by MXKhronos** [comment]
Fixed a case where bugged `blueprintpiece` without the custom name "Turret Blueprint Piece` was not letting players start the mission.
