### ISSUE TITLE
Bad backpack interaction on mobile

### ISSUE THREAD

**Issue by Atenbm** [HelixNebulaStudio/RiseOfTheDead#423]
Moving items between inventory and backpack is terrible on mobile
https://youtu.be/e1d7z-Eb4q0?si=jjDPWwSjTZH9InHh

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/506190ecba6208ca79042425c6243a2d1a14ee62
