### ISSUE TITLE
Everlast and Rocketman broken

### ISSUE THREAD

**Issue by Speedycar777** [HelixNebulaStudio/RiseOfTheDead#43]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/c27bf508-ff67-4191-9ee3-112068021983)
|
|
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/165123591/64e68b3f-3eb3-47e6-bbb6-d361cb497b77)

**Comment by MXKhronos** [comment]
Fixed unknown upgradeKey for `rocketmanmod` and `pyroeverlastmod`.
