### ISSUE TITLE
Hard Mode Vexeron - Body Became Fossil In The Air Or Became Tree?

### ISSUE THREAD

**Issue by SaibotAppend** [HelixNebulaStudio/RiseOfTheDead#431]
We fight and when attacks it ,the body of Hard Mode Vexeron is suddenly not moving eventually ,only sometimes his head pops it out away from its body and continue attack. Someone fix it?

**Comment by SaibotAppend** [comment]
![Uploading image_2024-06-04_105041388.png…]()

**Comment by SaibotAppend** [comment]
![Uploading image_2024-06-04_105300368.png…]()

**Comment by SaibotAppend** [comment]
![Uploading image_2024-06-04_105329808.png…]

**Comment by SaibotAppend** [comment]
[Uploading Screenshot 2024-06-04 105035.png…]

**Comment by SaibotAppend** [comment]
![image_2024-06-04_105359183](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/167265144/1005443e-1ba9-4426-9ef3-bf598dbcb39d)
This is approved

**Comment by 751234** [comment]
This has been a bug even as far as i can remember.

**Comment by SaibotAppend** [comment]
Of that ,I can't argue with that... If only your idea is to make new food items called 'Nekron Fruit' ,or 'N.E.D. MK1' ( Nekron Eradicator Device - it's like weapon feature of technology made from BioX but advance ) to make like that...
