### ISSUE TITLE
Belly of the beast, wont add a new dialogue option while i have the blueprint piece.

### ISSUE THREAD

**Issue by BongCloudMaster** [HelixNebulaStudio/RiseOfTheDead#432]
https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/126247984/070062ff-4c13-4ad0-aca7-dac522887a60

my user id is :1548381326, pls help

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/85422c43cef1c048791140b70bff8b7c7846b14c

**Comment by BongCloudMaster** [comment]
> [85422c4](https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/85422c43cef1c048791140b70bff8b7c7846b14c)

its still occurring
