### ISSUE TITLE
Factions feature requests

### ISSUE THREAD

**Issue by MrGarrettFerret** [HelixNebulaStudio/RiseOfTheDead#434]
Is it possible to add a display to the faction member statistics ui which displays the user's stats within a specific timeframe? This would be a very helpful feature for my faction (and likely others aswell) as we remove inactive faction members based on their total number of missions completed, but at the moment this is not really a good judgment for the user's recent activity as it only shows the total number of missions completed which doesn't account for the user's recent activity.

Another thing I'd like to suggest is the ability to see the amount of resources the faction has. At the moment you can't see _exactly_ how much a faction has of a particular resource, and this would be useful for knowing when to start missions like zenith and any other future missions that may have a large resource requirement.

**Comment by MXKhronos** [comment]
Hovering your mouse over your faction resources now shows the stat numbers.
