### ISSUE TITLE
Unable to progress Belly of the Beast

### ISSUE THREAD

**Issue by Geocraftery** [HelixNebulaStudio/RiseOfTheDead#435]
I got the 2 missing pieces inside of Elder Vexeron, then talked to Mysterious Engineer. The dialog worked as intended, however, the mission didn't progress to the next step (Sunken Salvages when available step) despite completing the dialog. I tried deleting one of my Blueprint Pieces as I planned to go back inside the Elder Vexeron to get more but it wouldn't allow me to enter it anymore. Now I'm left with 1 Blueprint Piece unable to get more, and the mission is still stuck at the "Talking about the last piece" part.

**Comment by MXKhronos** [comment]
#422

**Comment by Geocraftery** [comment]
@MXKhronos I progressed further from that fix, but now I'm stuck on a different part. When I wrote that issue I was on the first checkpoint. I'm currently on the fourth.
