### ISSUE TITLE
Hard mode Fumes can cover the whole room with gas.

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#442]
The hardmode Fumes covers the whole room with gases making impossible to beat it, this can be avoided by luring the fumes into the edge but theres one problem... sometimes the fumes is slow to walk due to the server age as the server becomes slow and can release gas while in the center making the Fumes cover the whole room with gas.

**Comment by MXKhronos** [comment]
This is intended and beating hard mode requires finding ways to survive being inside the Fumes Cloud.
