### ISSUE TITLE
The apostrophe symbol when used in chat partially shows the apostrophe in text.

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#445]
Example here:
![Schermopname (12794)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/087ce621-2a8a-4851-9960-a14a9f383ea4)

**Comment by Rookie21333** [comment]
also this one


![Screenshot (314)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/81686374-d4cf-4a72-9779-b8c93e5cdec7)

**Comment by Leroy8888** [comment]
Seems to be case for a lot of symbols
