### ISSUE TITLE
Bloaters burp

### ISSUE THREAD

**Issue by 751234** [HelixNebulaStudio/RiseOfTheDead#452]
I think instead of being a circle I think it would be better if it was only the particles.

Enhancement, sugestion

**Comment by MrGarrettFerret** [comment]
Disagree, the sphere helps the player see where the hitbox is. Particles are also lowered in quantity emitted and quality on low graphics settings, so particles alone would not be a good indication of an attack.

**Comment by MXKhronos** [comment]
True, particles in lower quality settings may have limited rates so they sometimes might not even be visible.
