### ISSUE TITLE
Turret Blueprint piece is still in my inventory after I completed belly of the beast quest

### ISSUE THREAD

**Issue by BongCloudMaster** [HelixNebulaStudio/RiseOfTheDead#458]
![RobloxScreenShot20240608_192927428](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/126247984/0ebd3c0c-09d3-4966-8db4-544a2ea5cc96)

I deleted some of the blueprints after completing belly of the beast quest, but the 1/2 turret piece is still in my inventory.
Fix this please

**Comment by MXKhronos** [comment]
Fixed in `2.1.9.2`
