### ISSUE TITLE
Zombies spawning out of bounds

### ISSUE THREAD

**Issue by Qureejjang** [HelixNebulaStudio/RiseOfTheDead#459]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162429221/b2f332c0-933b-4d77-977a-7907835b953f)

Could lead to some issues if a player does not have the means to kill them with explosives or shoot through the floor with the crossbow.

**Comment by MXKhronos** [comment]
Likely due to zombies falling through the floor when spawning.
