### ISSUE TITLE
Enemies under the effects of knockout can fly

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#460]

**Comment by Rookie21333** [comment]
Can confirm, even without knockback mod their ragdolled body flew like it has a maxed knockback mod

**Comment by MrGarrettFerret** [comment]
Can someone give more information on the issue?

**Comment by rafaderren** [comment]
> Can someone give more information on the issue?

Try hitting fumes with four knockback and one knockout with a crowbar

**Comment by rafaderren** [comment]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/b625c12c-8591-46f8-a2c5-baeaa6354a51)
the only proof i got about this problem
