### ISSUE TITLE
blueprint piece still remains in my inventory on the live branch

### ISSUE THREAD

**Issue by Boi2021Miceoos** [HelixNebulaStudio/RiseOfTheDead#474]
yeah that pretty much it
![Capture](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/86916029/ebb4d0d7-e228-4c18-baec-aee2d4c62869)

**Comment by MXKhronos** [comment]
You will need to talk to the Mysterious Engineer.

**Comment by Boi2021Miceoos** [comment]
alright
