### ISSUE TITLE
Zomborg prime stops attacking after his core is destroyed

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#475]

**Comment by MXKhronos** [comment]
I can't seem to replicate this during my time tweaking Zomborg Prime.

**Comment by Leroy8888** [comment]
I should've specified that this was specifically for his rocket barrage attack.

I cannot seem to replicate this anymore either. I am not quite sure what got changed to it in 2.1.11.0.

However, now it seems like Zomborg just doesn't move at all when the battle starts.
(https://gyazo.com/1b3192b8ec86d3d288432fbe075a200c)

**Comment by MXKhronos** [comment]
Haven't been able to reproduce this either.
