### ISSUE TITLE
Premium pass does not grant 9 active mission in the mission board

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#477]
Had a few people report this as an issue to me. I am unsure whether premium actually grants more active missions from the mission board.

I am premium myself and a max of 6 missions are always available to me.

Some people also report that they have up 9 mission active at a time.

**Comment by MXKhronos** [comment]
That was a bug where it miscalculated the amount of missions to add after for restock.
