### ISSUE TITLE
Chainsaw is able to be tweakable

### ISSUE THREAD

**Issue by MegatronOmegaV4** [HelixNebulaStudio/RiseOfTheDead#479]
So, i managed to tweak chainsaw with bug and high server ping
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/172412112/03309bb3-4878-4037-a5e4-e107c735c162)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/172412112/38cd4fee-ee6d-4762-aaa3-675739361038)

When ping is high (Like 400 or more) game breaks and thinks you tweaking for example REC-21 but in reality you tweak a chainsaw

**THIS BUG WORKS WHEN SERVER PING IS HIGH** (zombies should walk slower and game feels too slow)

**Comment by MegatronOmegaV4** [comment]
Average ping that i have is
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/172412112/029a51c9-6f6f-4c37-973c-de1f306f9f94)

**Comment by rafaderren** [comment]
I dont think its about server ping, it looks like when you quick click from your weapon to melee in the workbench the tweak button stays there it can only happen if you just used the workbench in the server for the first time
