### ISSUE TITLE
Player Character moving slowly on their own in First-Person Mode

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#484]
If a player goes into first-person mode, their character will, for some reason, slowly move backwards on their own. More noticeable if the player equips an item; it doesn't matter what item it is, and they will move forward instead of moving backwards.

**Comment by MrGarrettFerret** [comment]
Duplicate of https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/482
