### ISSUE TITLE
GPS QoL change suggestion

### ISSUE THREAD

**Issue by MrGarrettFerret** [HelixNebulaStudio/RiseOfTheDead#486]
A nice QoL change for the GPS would be making the interact (E press) perform the GPS's use function (toggle the fast travel UI) instead of the equip function, as most of the time when people equip the GPS they are only doing it to use it.

**Comment by MrGarrettFerret** [comment]
Looks like this was undone with some of the recent changes. Could this be re-added?

**Comment by MXKhronos** [comment]
Yeah, it was undone because it was causing problems with the hotkey handling order and the old implementation was kinda hacky. But I just thought of another way to fix it.
