### ISSUE TITLE
Bows becomes miscellaneous to the safehome survivors.

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#487]
![Screenshot (326)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/158ce19c-d1f1-4de1-b216-8de14350c036)

**Comment by MrPigZ** [comment]
Seems like the dialogue in which NPC complains about weapon being too complex for them to use is gone.

**Comment by rafaderren** [comment]
Flamethrowers cant be stored to NPC's aswell
