### ISSUE TITLE
toy gun skin perm does not work on the desolator heavy as it should be 

### ISSUE THREAD

**Issue by Boi2021Miceoos** [HelixNebulaStudio/RiseOfTheDead#489]
![RobloxScreenShot20240612_202940126](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/86916029/97158721-2cab-41f6-af13-1adb6f68ff8a)
it's not showing the supposed toy skin colour

**Comment by Leroy8888** [comment]
It seems to work fine for me. Did you apply the skin on that desolator specifically?
There's a section with ''Skins'' at the very bottom of the appearance menu. Make sure to check if the skin is currently being used on the gun.

It could also be that a clear texture was set on these gun parts. Try to reset them to their default state (including colors customizations). To do so, you would have to open the appearance menu in the workbench of the gun and use M2 (mouse right) on all of the weapon part boxes.

If done right the weapon should default to its original state. If a skin was used on it then it will default to the skin as well.

**Comment by Boi2021Miceoos** [comment]
nevermind, it was just clear texture was set on it thanks tho.
