### ISSUE TITLE
Ziphoning Serum

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#49]
New board mission, Ziphoning Serum. Rachel requires some items to create some Ziphoning Serum.

Reward: +10 Perks

New food, Ziphoning Serum. Cleanse cleansable debuffs and gives you the Ziphoning buff for 3 minutes.

The Ziphoning buff gives you health per second based on the ziphon health pool, the ziphon health pool only fills up when you do damage to enemies.

Use duration: 1 second. Effect duration 3 minutes.

**Comment by JakobCh** [comment]
Ran into some problem with the daily missions when I was going to test this, I can only see 3 even tho is says there should be 7.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/278e46fd-d654-4c7a-a41c-1b3576f9fd41)

**Comment by MXKhronos** [comment]
> Ran into some problem with the daily missions when I was going to test this, I can only see 3 even tho is says there should be ..

Couldn't pinpoint the cause, replaced reward text for better debugging.

**Comment by JakobCh** [comment]
> > Ran into some problem with the daily missions when I was going to test this, I can only see 3 even tho is says there should be ..
> 
> Couldn't pinpoint the cause, replaced reward text for better debugging.

All the missions load in now, maybe this was the problem:
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/43d06072-a8f1-487e-8ff3-3aaac86b247b)

**Comment by MXKhronos** [comment]
Fixed `Coming To The Rescue (48)` reward configuration.

**Comment by JakobCh** [comment]
Alright I played through the mission and it worked fine. Ran Sunken Ship to get the materials.
Feels kinda weird to have to turn in the items through a trade window instead of just through dialog.
Maybe only getting 3 serums a day is too little? Saw there was a mod that was affected by it but I haven't tried either yet. You could maybe make it so you can turn it multiples of the materials to get more.

**Comment by JakobCh** [comment]
I noticed the trading button doesn't seem to round it's countdown number.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/e7377b78-5be7-46fb-b00b-70b271f99680)

**Comment by JakobCh** [comment]
The tool tip on the buff starts out reading "+$Amount hp/s", after you deal damage it works fine until it drops down to 0 then it gets stuck on 1hp/s, even if you damage another zombie.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/0ca84c30-ea37-4006-99bf-839b38476c21)

**Comment by JakobCh** [comment]
The serum seems to always heal 1hp even if you have a higher stack, tested with a stack up to 130. Probably the same problem as my previous comment.
I also noticed that you can gain a lot of stacks from using shotguns easily reaching 100+.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/8f4377ed-12e3-43bd-8939-d8b947789daa)

**Comment by MXKhronos** [comment]
- Fixed + $Amount hp/s label
- Added additional information to `ziphoningserum` description.
- Mission now drops 5 instead of 3. 

+ 1hp/s is intended, this is a base value. Having Nekrosis Amplifier on your chest armor increases this value.


https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/188424567846f8077d034677f89777ab58543e43
