### ISSUE TITLE
Vexeron not inflicting damage

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#494]
Vexeron is unable to damage players when they come into contact with his bristles, allowing players to freely go near and easily defeat him without the risk of being attacked by him at all.

**Comment by Leroy8888** [comment]
Very likely related to this error log: 
![Schermopname (12939)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/3c5ca989-b4f0-4215-84a7-fa5757977029)

This error also seems to cause issues with Vex' pathfinding towards the target as Vexeron doesn't seem to directly charge at the player anymore.
