### ISSUE TITLE
Lower the health of the barricades in Factory raid

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#507]
They currently stand at a whopping 5k, which is quite a lot for a new player. It's not impossible to get through, but I feel like it would be a greater experience if they instead were lowered to about 500 health each.

**Comment by zkkuu** [comment]
Aren't the doorway barricades, both in Factory and Abandoned Bunker, scale with a player with the highest mastery level in the lobby?

> 2.1.10.0
- Doorway Barricades in raids now scales with raid difficulty, maxHealth = difficulty *100, difficulty is based on the player with the highest focus level in the lobby.
- ...

**Comment by Leroy8888** [comment]
My bad, didn't see this change
