### ISSUE TITLE
Bandits fall into the void in W.D. Underground while playing 'High Value Package'

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#518]
If the player enters W.D. Underground with the mission 'High Value Package' at the objective of delivering the package, 2 bandits will spawn at the entrance to W.D. Warehouse's collapsed island, the second spawning shortly after the first. However, these bandits will fall into the void immediately after spawning.

This bug can be avoided by not entering W.D. Underground while playing 'High Value Package'.
This bug was encountered while playing the game on a computer.
The version on which this bug was encountered is 2.1.4.?.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/26fe6181-a0d1-459d-9910-5df0c6843756

**Comment by Leroy8888** [comment]
Mentioned in #408
