### ISSUE TITLE
Consider bringing back the old system for throwing pointed melees

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#519]
Currently, throwing a pointed melee with the reticle at an object within range will cause the projectile to land on the object. This seems simpler for players in theory, but with the relatively slow projectile travel speeds (even on a non-bugged server), when the target is moving, the projectile will usually not hit the target unless the target is within close range because it simply takes too long for the projectile to travel to the target. This becomes particularly bad when a server is bugged, causing throws to fly over the target when not within melee range. This defeats the purpose of having a ranged attack and the only way to rectify this is to throw at the floor in front of the target so that the projectile goes into the target, which is less intuitive than aiming higher with the old system.

Examples (both servers are bugged):

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/6f93723e-6588-44db-b139-75bb53bbd502

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/699bb9a8-a4b5-4e5c-afc6-d0281fdcc988

**Comment by ShatteredVoidCrystal** [comment]
dramatic ahh throw
