### ISSUE TITLE
Some W.D. Underground servers repeatedly and randomly slow the player with no obvious cause

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#520]
There does not appear to be anything new in the Developer Console.

This bug can be avoided by leaving bugged servers.
This bug was encountered while playing the game on a computer.
The version on which this bug was encountered is 2.1.13.?.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/94d4823d-a44a-4386-981b-03c2fdcfd420

**Comment by zxcvbgfrtyui** [comment]
I think that I've encountered this bug at least 3 times, have definitely encountered it 2 times. I don't encounter the bug outside of W.D. Underground and rejoining a bugged server will cause it to occur again, so I don't think it's a problem with the player.

**Comment by zxcvbgfrtyui** [comment]
I think I've identified the cause.
https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/4cb74b58-59db-4ca8-b4db-a5941655f969

**Comment by Leroy8888** [comment]
I suppose not, but what did you do to make them act that way? To me, it does seem like they're missing a body part. Similar to how bloater behaved before their rework.

To give a quick summary of that bug, when bloater parts were blown off with a shotgun they would fall down onto the ground unable to move. But what actually ended up happening is that the model of the NPC stopped moving while the entity was in fact invisible. spawning some sort of ''ghost''. The entity at that state could only be damaged if the player found the bugged body of the entity and shot it.

Though the above does deal damage to the player.

**Comment by zxcvbgfrtyui** [comment]
I didn't do anything to them other than spawn in at that entrance and immediately move away before they could detect me. They may have been led there by another person and become stuck in a loop where they attempt to attack the non-existent player, which happens to hit anyone who spawns there.

**Comment by zxcvbgfrtyui** [comment]
It's additionally very unlikely for them to be invisible, because that would require them to consistently catch up to me, even while I'm slide-jumping and even when I'm in a safehouse.

**Comment by zxcvbgfrtyui** [comment]
I should note that attracting the attention of the zombie(s) responsible or killing them will resolve the problem.
