### ISSUE TITLE
Invisible object in W.D. Underground

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#536]
This bug can be avoided by avoiding the affected area.

This bug was encountered while playing the game on a computer.

The version on which this bug was encountered is 2.1.13.?.

[https://youtu.be/Sh4Jdf0xZD8](https://youtu.be/Sh4Jdf0xZD8)

**Comment by Leroy8888** [comment]
This seems to appear randomly in that map, more commonly in older servers. Fresh servers or VIPs never seem to have this issue. It might be a loose brick or seat being moved.
