### ISSUE TITLE
Fission Bay Endless is impossible! (forgot tags but its a bug)

### ISSUE THREAD

**Issue by ShatteredVoidCrystal** [HelixNebulaStudio/RiseOfTheDead#538]
Once you do endless in Fission Bay, and you reach an extreme boss wave and Vein of Nekron spawns, he doesn't spawn in, making Fission bay impossible!
https://youtu.be/WR6Yf0Ju1gk
accidentally posted a clip of my friend snoring mb
the actual video was too large though, so i had to put it on youtube, sorry.

**Comment by ShatteredVoidCrystal** [comment]
Sadly the video file is too large
I'll try to compress it somehow
hopefully its still able to be read

**Comment by ShatteredVoidCrystal** [comment]
screw it im putting it on yt

**Comment by mega00913** [comment]
Can confirm. Another point to note is that zombies do not spawn during a VoN boss wave.

**Comment by ShatteredVoidCrystal** [comment]
thanks konos
