### ISSUE TITLE
The game occasionally crashes when joining a world server

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#539]
The game does not crash with an error message. It simply closes the application, but is sometimes preceded by a short screen freeze.

This bug cannot be avoided. It can occur when joining the game from the main menu or returning to a world server after finishing a raid, co-op, survival, etc.

This bug was encountered while playing the game on a computer.

The version on which this bug was encountered is 2.1.13.2.

As the application closes unexpectedly and almost immediately after joining the server, it is not possible to check the Developer Console or record a video of the bug.

**Comment by zxcvbgfrtyui** [comment]
This bug can also occur when travelling between worlds.

**Comment by Leroy8888** [comment]
There also has been a bug report in the unofficial server about a crash related issue. However, that issue occurs when players attempt to kill entities and I haven't been able to figure out what causes it as I've never experienced it.

Someone in that thread mentioned that the desktop VR might've been the cause as disabling or deleting that app reduced the screen freeze time.

Though, that aside. This issue seems to a new variant of the crash? Does this occur more often in specific worlds?

**Comment by zxcvbgfrtyui** [comment]
It seems to occur for any world, can't recall any examples right now.

**Comment by Leroy8888** [comment]
Is this specifically when joining a server? And does this also occur if you interact with a zombie?

**Comment by zxcvbgfrtyui** [comment]
Only when joining a server. I have never been able to get to the point of seeing a zombie because I crash in 5 seconds tops after leaving the previous server. This is not 5 seconds after being able to view the new world through the camera, this is 5 seconds after the screen going grey or showing a background picture during the server transition.

**Comment by Leroy8888** [comment]
Alright, lastly. You state that occurs only when you return to Pub worlds like warehouse.

But it does not occur when you travel to a raid, safehome, survival or anything that creates a new server?

**Comment by zxcvbgfrtyui** [comment]
It has never occurred when travelling to a new server as far as I'm aware, but it could be that a new server is being made because I can't tell. It may be by chance, but I have crashed about 5 times like this and none of them were from anything that always creates a new server.

**Comment by Leroy8888** [comment]
No I am less leaning towards a specific action or something that happens in Public worlds while you travel to them. 

At first I didn't think it would be connected to #548 but it might.
