### ISSUE TITLE
Is the Cultist Hood supposed to deceive cultists in any way or is it just a cosmetic?

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#540]
I've seen some people in the past state that it's supposed to decrease the chances of a cultist spawning or make them not spawn at all, while others state that it's merely cosmetic, and it seems to have been unanswered for a long time.

**Comment by MXKhronos** [comment]
It doesn't change the spawn rate of Cultist. It was just cosmetic, but I just added a passive effect to the `cultisthood` for `2.1.15`.
