### ISSUE TITLE
Fission bay zombie pathfinding is still broken

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#542]

**Comment by mega00913** [comment]
I would like to request more information about this, as I have experienced minimal issues regarding pathfinding during my own playthroughs.

**Comment by rafaderren** [comment]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/4630582e-f252-4397-91ac-6a817aef8013)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/5761d361-b647-4226-86e7-d4114897d437)
Zombies still get stucked at this spot, this has been reported and fixed but its still there.
https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/340
