### ISSUE TITLE
Waist rotation bug

### ISSUE THREAD

**Issue by OnyxHoundov** [HelixNebulaStudio/RiseOfTheDead#547]
Some melee weapons shown in this video retain waist rotation after attacking with broom spear.

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162656934/8956cf6a-6247-4aa8-b350-653cb591eb7d

**Comment by Leroy8888** [comment]
Seems to be related to this log 
![Schermopname (12975)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/3590548d-217f-4c1b-905c-49cbc9313a88)
