### ISSUE TITLE
Warmonger's Scales increases oxygen time

### ISSUE THREAD

**Issue by ShatteredVoidCrystal** [HelixNebulaStudio/RiseOfTheDead#551]
Warmonger's scales increases water breathability time? (Also <b> roleplay name glitch haha)
The clip is of the bug in action, alongside with swapping your armor with warmonger to scuba suit.
https://youtu.be/bJP81X7b2v8
if you're reading this tell me how to put tags on my titles idk how to 😭
I dont think i have label access so i'll just say the labels myself, Live Branch, Bug, and its probably a minor issue.

**Comment by MrPigZ** [comment]
From 1.5.5 update log: "• Swimming underwater now cost oxygen, you will naturally have oxygen capacity equals to your health. You drain oxygen when your head is underwater."

More hp you have more oxygen you have.

**Comment by ShatteredVoidCrystal** [comment]
alr good to know
