### ISSUE TITLE
Rachel clothing is weird...

### ISSUE THREAD

**Issue by AndrewBuggeinator** [HelixNebulaStudio/RiseOfTheDead#553]
![RobloxScreenShot20240629_105441501](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/86916029/d245cd6b-58dd-4827-962e-2e95b6a05d23)
yeah i don't know why it happens or how it even happened

**Comment by MXKhronos** [comment]
Loading issue on the client side, usually related to low harddisk space.

**Comment by AndrewBuggeinator** [comment]
ok
