### ISSUE TITLE
The flamethrower is flipped sideways when attempting to inspect it

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#556]
![Schermopname (13039)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/684176c7-6015-4dea-9dd3-87f7f591db20)

**Comment by zkkuu** [comment]
Not just the Flamethrower; this also applies to some of the guns that recently got their models reworked, such as, but not limited to, the Desert Eagle and the Grenade Launcher.
