### ISSUE TITLE
Brown Leather Boots Visual Bugs

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#560]
The player's lower legs does not disappear when they are wearing the Brown Leather Boots. As a result, it leaves their legs sticking out of the boots.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/3c25f45e-1878-406f-835f-f4cbd53d6aff)

The same applies with the feet when previewing the boots in the workbench.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/ee14d11b-e4b2-41e3-8211-28684323b906)

**Comment by MXKhronos** [comment]
Fixed foot showing up in workbench, but I'll need steps reproducing the first part where foot not hidden while wearing them.

**Comment by zkkuu** [comment]
> Fixed foot showing up in workbench, but I'll need steps reproducing the first part where foot not hidden while wearing them.

The player's feet are fine, what I meant was the player's **lower leg**, not their feet. Before, wearing the boots would remove one's lower legs and feet so that they didn't appear to stick out of the boots.

Now, the feet do get removed, but not the lower legs. Thus, the ends of the lower legs stick out of the boots. This can be proven by looking inside the boots worn by the player and Hector Shot via freecam.

![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/f1a8bb3f-9e7b-4c2c-9411-b638277e5701)

![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/3f5888e7-3c45-4aee-ab79-6f05531ab18a)

![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/c1ff767e-e68c-4c9b-811d-89d0f95e93ef)

**Comment by MXKhronos** [comment]
Ah, I see.
