### ISSUE TITLE
Random trade errors when interacting with icarus.

### ISSUE THREAD

**Issue by starlintons** [HelixNebulaStudio/RiseOfTheDead#572]
![Screenshot 2024-07-03 at 12 39 26 PM](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171533555/4e6775fa-80df-4027-aba4-841780315ae2)
Trading with no one

**Comment by starlintons** [comment]
Free 1 million gold.

**Comment by MXKhronos** [comment]
Those are just placeholder values when trading with no one from failing to interact.
