### ISSUE TITLE
Magazines and ammunition parts lose their colour when player reloads

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#573]
After a reload texture becomes completely visible which causes this issue.
https://www.youtube.com/watch?v=-SwE7RpodyI

For some reason desolator bullets keeps their colour.
https://www.youtube.com/watch?v=DD50RpHiPXY

**Comment by MXKhronos** [comment]
Could you screenshot/ copy and paste the values here? 
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/38783502/e91576d2-f6e5-43df-942b-d9cdc357fb3a)

**Comment by MrPigZ** [comment]
This happens with the old customization system as well with the new one.

Currently in the new system customizing ammunition doesn't remove the base texture. 

I don't have the same m4a4 but this one has same issue:
{"Plans":{"[All]":"#0000ff;skinhexatiles_v2;0;#ff00bf,,,,,56;;;;100,100,100;","Magazine":";;;,,,,,;;;;100,100,100;"},"Layers":[]}
