### ISSUE TITLE
W.D. Warehouse still has the crashing bug

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#574]
[This commit](https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/651ade357859fe266a2003ccf5d9f5468a5b32c5) is supposed to fix the crashing bug on W.D. Warehouse but I still experienced it on my phone and someone else who said they got the crash twice
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/221bbe85-0a63-4f2d-84de-1150e970807d)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/3e015731-1485-474e-bd9f-c9abad8ad81b)

**Comment by MXKhronos** [comment]
I'll need to slowly isolate the issues in order to fix potential crash cases, until I can get a concrete steps to reproduce the crash, I can only tweak/rewrite a bunch of stuff to see if it helps.

**Comment by MXKhronos** [comment]
Sound memory usages reduce significantly to help reduce crashes that may be caused by client using too much ram.

**Comment by rafaderren** [comment]
The sound memory usage fix seems to fix it for me, i havent gotten any crashes on my phone so far but im not sure for other people with weaker processor
