### ISSUE TITLE
Gumball's buff reinforcement has issues

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#58]
They cannot move and shoot at the same time. If they walk they will put their weapon away.

Their melee attacks damages the player.

They may aggro on NPCs (in warehouse they only attacked Jesse and Mason). They also might attack each other. If the rat shopkeeper has a broomspear they can kill Mason.

**Comment by MXKhronos** [comment]
Fixed npc re-equipping weapon when it's already equipped. Fixed melee damaging players. Fixed targettable npcs.
