### ISSUE TITLE
Store usage and storage slot unlocking QoL

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#588]
This change dates back quite a long while, but when I was looking into the 4th storage page it reminded me how tediously slow it can be to unlock it and it also made me throw a glance at the store.

Currently, each time you want to unlock a storage slot you have to interact with the crate, select a page, click an empty storage slot and then confirm your purchase with perks and repeat that 50 times. It would be nice if it stayed open on the same page after a purchase or if the ability was granted to buy multiple slots at once.

Additionally for the (RAT) store, it always seems to close the moment something is traded. It's especially noticable when the player tries to sell something that has a stack size of 1. If either multiple stacks could be sold at once or a set amount of items could be bought at once it would improve the general usage of it. The store could also remain open after purchase, which would also help to make using it less tedious.

**Comment by MXKhronos** [comment]
Remade the ancient prompt box with a new one, it'll support dynamic scaling to fit more text & buttons when needed, let me know how it feels. It should also feel more responsive and no longer closes all menus when pop up. Clicking off the frame will close the pop up.

**Comment by Leroy8888** [comment]
It looks good. It's seems smoother in the transition and also feels faster overall.

However this menu does seem to be missing from the gold donation leaderboard, which still uses the old prompt and looks. Same thing for the event passes if the player wants to buy some levels with gold and the workbench when perks are used to speed up recipes in it.

It also uses the old menu for survivors in the safehome when tasks are assigned to them, but it doesn't close the menu if these tasks are sped up with gold or perks.

Despite this, unlocking storage slots and buying items is still somewhat slow if large quantities are prefered. Maybe increments of 5 or 10 could be added for stackable items like blueprints when bought from a vendor? It could also see use in unlocking multiple storage slots at once.

**Comment by MXKhronos** [comment]
Yep, I'll be slowly transitioning from the old prompts to the new one depending on priority.

As for a more custom quantity actions, that'll require more work, I'll see what I can do.

**Comment by zkkuu** [comment]
The new prompt looks very good; however, I do have one small complaint.

Attempting to sell multiple items will not correctly display the amount of money you would get for selling them. That's pretty much it.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/ee7043d2-0fec-4687-8e9c-e7047556b865)

**Comment by MXKhronos** [comment]
Fixed the sell all price.
