### ISSUE TITLE
Clothing skins can be overriden with other skins

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#591]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/04b0b75f-5f55-4d33-9c47-9c20982ad125)

https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/76096781/db2aa6c7-5be6-49f2-9919-92009dd48e8e

**Comment by Leroy8888** [comment]
If it wasn't for the possibility that this can be used as a way to fool people into thinking they can obtain something looking like this, it would've been a harmless addition to keep.

This default back to normal when changing servers or re-equiping the item
