### ISSUE TITLE
bug ( lost item)

### ISSUE THREAD

**Issue by goblin-04** [HelixNebulaStudio/RiseOfTheDead#594]
my item has been deleted out of inventory no reason, i just check all storage and somewhere but didn't see it , please fix it and refund item to my inventory.im lost 1 night vison goggle and p.a.t

**Comment by MXKhronos** [comment]
Please direct message your Roblox profile to us and we'll check your data for loss items.

**Comment by goblin-04** [comment]
https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.roblox.com%2Fusers%2F614718113%2Fprofile&h=AT3FcxCIWydUQ3RhCgNkCCkRSgADI0Wu5-78LbXylmgPhk76SuZK_gLZC8-qml1-Ui_TFI_wGybXGXN4Li8JWHSKXDc570t0JC2MjVTRy7ebr7guDOvHvGbKFZDUskx0CFug43KWCmSjSjI&s=1

Vào 02:06 PM, T.3, 9 Th7, 2024 Khronos ***@***.***> đã viết:

**Comment by goblin-04** [comment]
https://www.roblox.com/users/614718113/profile

Vào 02:06 PM, T.3, 9 Th7, 2024 Khronos ***@***.***> đã viết:

**Comment by MXKhronos** [comment]
Your items are back in your inventory.
