### ISSUE TITLE
bug lost item and bug premium inventory

### ISSUE THREAD

**Issue by goblin-04** [HelixNebulaStudio/RiseOfTheDead#598]
i got bug make me lost item again but now it is very bad . im lost items and the bug make i can access to premium inventory in spite of i didn't buy premium gamepass , pleaae fix it again help me.Thanks

**Comment by MXKhronos** [comment]
Please send your profile again.

**Comment by goblin-04** [comment]
https://www.roblox.com/users/614718113/profile

Vào 02:09 AM, T.5, 11 Th7, 2024 Khronos ***@***.***> đã viết:

**Comment by MXKhronos** [comment]
Could you describe what happen that lead to the item loss?

**Comment by goblin-04** [comment]
i dont know why but that day i just joined game for check my items are
refund or no and i saw my inventory loss items and sunken ship raid'
crate.Before i got a bug when i complete sunken ship raid. When im exit and
got a bug to made me loss item
