### ISSUE TITLE
(Dev branch) Aiming down weapon sights in FP is slightly off center

### ISSUE THREAD

**Issue by HelixNebulaStudio** [HelixNebulaStudio/RiseOfTheDead#6]

**Comment by MXKhronos** [comment]
Most weapons are getting reanimated and some getting a new model too by Daniil.

Here's what's completed:
- [x] ak47
- [ ] arelshiftcross
- [ ] at4
- [x] awp
- [x] cz75
- [x] czevo3
- [x] deagle
- [x] desolatorheavy
- [x] dualp250
- [x] flamethrower
- [x] fnfal
- [ ] grenadelauncher
- [x] m4a4
- [ ] m9legacy
- [x] mariner590
- [x] minigun
- [x] mp5
- [x] mp7
- [x] p250
- [x] rec21
- [x] revolver454
- [x] rusty48
- [x] sawedoff
- [x] sr308
- [ ] tacticalbow
- [x] tec9
- [x] vectorx
- [x] xm1014

**Comment by OnyxHoundov** [comment]
Grenade launcher reanimation is done

**Comment by OnyxHoundov** [comment]
Weapons reanim's done

**Comment by MXKhronos** [comment]
All reanimated.
