### ISSUE TITLE
The polaris skin cannot be bought from the gold store

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#608]
It instead gives you this error and an empty menu.

Side note, I did not opt in, but it also occurs if you're.
![Schermopname (13207)](https://github.com/user-attachments/assets/e0b087ef-3ba3-425e-9615-4a553cbaaab5)

**Comment by MXKhronos** [comment]
The skin perm isn't selectable in the gold shop if you're aren't opted in. It's just trying to preview the new skin perm using the old system.

**Comment by Leroy8888** [comment]
okay, it appears it function now. It appears I opted out once I traveled to warehouse from harbor. I didn't interact with a lot of weapon or tools, so it probably didn't correctly opt me in?

But when I wasn't opted in all I did was open the gold shop, go into special items, then new items and select either ''All'' or ''Tool'' under Quick search.

**Comment by MXKhronos** [comment]
This will be accessible in gold shop without optin once new customization menu is out.
