### ISSUE TITLE
Weapons have a chance to load a free shot instead of actual ammo after killing targets and reloading

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#609]
After killing at least one target with the last unit of ammo in the weapon (not reserves) and reloading, when the player fires their next shot, there is a chance that the ammo count is reset to just before the reload. This effectively provides players with free ammo at the cost of having to reload after each shot. This bug can occur multiple times in a row and is especially likely to occur when large numbers of zombies are killed at once, which is easily done with maxed Explosive Radius mods on explosive weapons such as the Grenade Launcher and AT4.

This bug can be avoided by killing enemies with non-ammo weapons instead.

This bug occurred while playing the game on a computer.

The version on which this bug occurred is 2.1.17.1.

[https://youtu.be/jNzAX_VB8Ik](https://youtu.be/jNzAX_VB8Ik)
![Roblox 14_07_2024 6_08_18 AM](https://github.com/user-attachments/assets/5de21e96-f093-49a7-b0c3-7eac593639d9)

**Comment by Leroy8888** [comment]
Seems to be issue #199

**Comment by zxcvbgfrtyui** [comment]
They are probably related, but not the same. This specifically requires that a target be killed to trigger it. I have tested without killing anything and it does not occur at all without kills. I also cannot replicate the bug in that issue on the live-branch.

**Comment by MXKhronos** [comment]
This is certainly hard to fix, I have yet to come across a solution that doesn't hinder the experience due to latency when the server and client have to sync ammo counter. This is negligible for now because it's suppositely intentional until there's a solution.
