### ISSUE TITLE
Carlson doesn't give the player scrap In `safety safehome` 

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#610]
Player won't recieve any scrap from named character after recieving it from the stash, despite him clearly mentioning that you'll use the metal from his stash.

![Schermopname (13212)](https://github.com/user-attachments/assets/bf371ed4-c946-4515-a723-c9dd82c95ba0)

**Comment by Leroy8888** [comment]
I might be mistaken, but I believe this issue dates back quite a bit. Will need a bit of clarification whether it's exclusive to dev branch that you can build the barricades without having enough scrap.

**Comment by MXKhronos** [comment]
You receive it after completing the mission, I've change the dialogue a bit to be more clear. Since you gave the 1k scraps in the previous mission The Backup Plan, building the barricades are free because you're using Carlson's metal.

**Comment by Leroy8888** [comment]
Alright, I appears you cannot build the barricades even if you give Carlson the metal.

So if you give Carlson all the metal, you would have to grind another 500 to finish the mission. Which is quite the task for a new player.
