### ISSUE TITLE
Premium 4h storage page slot purchasing (main branch)

### ISSUE THREAD

**Issue by MemenTheMeme** [HelixNebulaStudio/RiseOfTheDead#611]
Non premium members are able to purchase slots for the premium only 4th storage page, even though they cant use it

**Comment by Leroy8888** [comment]
I am not sure if this is really an issue, since they could buy them in preperations for actually buying premium. But i'll mark it down.

**Comment by MXKhronos** [comment]
Intended, for if they reached perks cap and have nothing to spend perks on.
