### ISSUE TITLE
how do i return back to the old lighting of the guns 

### ISSUE THREAD

**Issue by wassagbruh** [HelixNebulaStudio/RiseOfTheDead#615]
Cause it sorta hard now to see things in the dark with the new lighting, and I just personally like the old one better 
![RobloxScreenShot20240714_191937147](https://github.com/user-attachments/assets/2c100276-a55c-42e6-bc6f-2c1c9c775664)
you see that the new lighting is now just an circle

**Comment by AndrewBuggeinator** [comment]
and yes my rng is bad with the NVGS so don't bother saying use the nvgs and im quite bored

**Comment by Leroy8888** [comment]
This was a change made a bit ago, since the ironsights reflected light coming from the main gun.

However, this was also present from any light, be it artificial light in-game. So it partly solved the issue, but not entirely.

There's no way to revert it atm, but maybe it could be made an option.

**Comment by wassagbruh** [comment]
Yeah I can see this as an option for the settings considering the fact the old one just made blackout waves abit more easier to see.

I don't hate the new lighting of the guns, but it kinda look weird for me seeing me used to the old one.

Also, How much perks total for the 4th Storage for the Safehouse Storage? Just wondering btw.
