### ISSUE TITLE
Unable to start the railways raid

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#621]
Unable to interact with the controls to start the train once the chains are broken (https://gyazo.com/017a0a0580798c574dbaf7387b817e23)

it also appears that entering this raid resets all the player's Settings.

The following error also appears in the log, but likely isn't related to this issue.
![Schermopname (13223)](https://github.com/user-attachments/assets/8efcbf65-ed75-4495-a938-6d422d2a4382)

**Comment by MXKhronos** [comment]
I couldn't replicate the issue, but I think place may have been outdated, it's updated now.

**Comment by zxcvbgfrtyui** [comment]
This issue still exists, leaving mining as the only renewable way of getting Coal, which is annoying because it's also heavily reliant on other players being present in the server, but not mining the Coal themselves. Exists as of 2.1.19.0.
