### ISSUE TITLE
Railways Train controls will not function.

### ISSUE THREAD

**Issue by choppygraph** [HelixNebulaStudio/RiseOfTheDead#622]
![image](https://github.com/user-attachments/assets/29aee437-fd57-4f0d-85db-c989660aee34)
Image taken from Mcgriddles.
Railways is currently unable to completed due to this, the train cannot start.

**Comment by rafaderren** [comment]
Still havent been fixed as of 2.1.20
![image](https://github.com/user-attachments/assets/79c97166-4775-4424-9428-a584dcfdad93)
![image](https://github.com/user-attachments/assets/63c1f462-8301-4822-bd20-6cb415d87d52)
Side note settings get reset everytime you enter the raid and the faction menu gets locked even being in one or finished Double Cross
![image](https://github.com/user-attachments/assets/8bb31f82-ed80-4b13-808c-3860cdcea700)

**Comment by rafaderren** [comment]
This issue is still persisting.
- Settings still gets reset
- You still cant open the faction menu
- UI still doesn't check for player progression
- You cant obtain the Railway Crates
![image](https://github.com/user-attachments/assets/90b38462-f352-4ceb-8ce1-0e5b828711f0)
