### ISSUE TITLE
Pattern Permanent Icons

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#625]
Khronos, can you add in the new pattern permanent icons to the game asset repository for the Rise of the Dead wiki?

**Comment by zkkuu** [comment]
Unrelated, but can you also make color pack icons for Dull, Army, and maybe even the unreleased Abyss and add them to the game asset repository as well?

**Comment by MXKhronos** [comment]
Added polaris, dull and army to asset repository.

**Comment by zkkuu** [comment]
Since the Abyss color pack is now added, can you add its icon to the game asset repository as well as the Cute But Scary and Halloween Pixel Art pattern permanent icons, Khronos?
