### ISSUE TITLE
Polaris skin perm shows nothing in gold shop

### ISSUE THREAD

**Issue by AureliusAurie** [HelixNebulaStudio/RiseOfTheDead#626]
![Screenshot 2024-07-18 023328](https://github.com/user-attachments/assets/b7a94f5d-b23b-49f5-b6de-94564457e3f0)

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/608#issuecomment-2234010246
