### ISSUE TITLE
Wither

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#64]
`/spawnentity Witherer`

- They only spawns if there’s a nearby wall or ceiling, generally ceiling.
- They applies a Withering debuff on players which continuously drains their armor until 0.
- They generally have a large amount of health. base: 1024hp, +1024hp per level.
- If you shoot the eye, they will hide and be immune for 7-11 secs. Best way to clear them are high dmg single shot weapons. Especially a high level Witherer, they can have up to `56*1024  = 57'344 hp`
- They also hide if player is too far.

**Comment by Leroy8888** [comment]
A comment on the trello card stated they spawn in TheUnderground, but I haven't really seen any thus far. How likely are they to spawn and when do they do so?

**Comment by MXKhronos** [comment]
> A comment on the trello card stated they spawn in TheUnderground, but I haven't really seen any thus far. How likely are they to spawn and when do they do so?

They spawn every 20 zombie kills in a 64unit region.

**Comment by JakobCh** [comment]
I managed to get 2 to spawn.
Took a lot of kills but I assume it's supposed to be rare, especially on a public server.
You seem to gain the debuff icon as soon as it sees you, not when the actual damage kicks in.
It can also apply the actual damaging debuff while it's hidden.
![RobloxScreenShot20240404_170735716](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/9ddccedf-0a3b-44aa-b830-9ad8ef037f57)

![RobloxScreenShot20240404_171716893](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/71753b46-1fbd-49d2-b67b-40209964ef29)

**Comment by MXKhronos** [comment]
That was intended but I guess it makes sense to damage when the Wither can see you.

**Comment by JakobCh** [comment]
> That was intended for the debuff to keep doing damage as soon as it's activated but I guess it makes sense to damage when the Wither can see you.

If you already have the debuff on you I think it doing damage while the wither is hiding is fine.
I more had a problem with the fact that the debuff can start damaging you while it's hiding.
