### ISSUE TITLE
ROTD The Engineer Badge Bug

### ISSUE THREAD

**Issue by RLTP21** [HelixNebulaStudio/RiseOfTheDead#652]
I just bought the engineer game pass today. I received the game pass but did not get any of the badge from it or the perks.

I tried rejoining the game and resetting my character, but these 2 methods did not work at all.

PC

I experienced this issue in-game 

version 2.1.21.1 (Live)

Pics:
![The Engineer Badge Unowned](https://github.com/user-attachments/assets/c2bde4b0-f522-4df7-80b3-f87482e8356a)
![ROTD The Engineer Badge Bug 2](https://github.com/user-attachments/assets/af938199-a9ab-461e-a723-9c064f75065f)
![ROTD The Engineer Bagdge Bug 1](https://github.com/user-attachments/assets/be1c38ab-43b5-4cbd-b968-17424f115a44)

**Comment by Leroy8888** [comment]
This issue might be linked to #640 , may be the way the game gives out badges or handles the privileges. 

As clarification, the portable workbench can still be used in this state. It's just the badge.

**Comment by RLTP21** [comment]
Also to add more information to this issue, I bought the VIP traveler game pass first and then the portable workbench one last. When I rejoined the game to get the 2 badges, It only gave me the VIP badge one but I did not receive the 2nd badge for the workbench one 
![VIP Traveler](https://github.com/user-attachments/assets/75ebabc3-044c-41c8-b6a1-ca7690d7b91b)
