### ISSUE TITLE
Not interacting with the park gate in `Vindictive treasure 1` after defeating Zricera won't progress the mission.

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#658]
Self explainatory title.

Staying the in the lobby to get kicked out when the timer expires forces you to redo the boss, so does any other action besides interacting with the gate.

**Comment by Leroy8888** [comment]
Note, this issue might actually be tied to #212 as it seems that this occurs in between the lines of the states issue

**Comment by MXKhronos** [comment]
Yeah, this was an issue where exiting the boss arena is handled differently between leaving by interaction or leave by expire timer.
