### ISSUE TITLE
Wooden crate not accesible in side mission The Backup Plan

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#66]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/6fa1f998-08d1-4b07-9b19-3045e5b68edc)

**Comment by MXKhronos** [comment]
Can't seem to replicate this bug.

**Comment by MrPigZ** [comment]
After lot of testing I cant come up a consistent way of replicating this issue. Sometimes it happens and sometimes it doesn't. Rejoining does fix the issue.

**Comment by MrPigZ** [comment]
After another set of testing it seems like the issue happens when player completes mission A New Community and right away start doing mission The Backup Plan.
