### ISSUE TITLE
Mobile players cannot push the statue in `vindictive treasure 1`

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#660]
I am not 100% if this is exclusive to mobile, but I cannot test it myself since I do not have a mobile platform to do so, not a emulator for it. It doesn't seem like it appears on PC and the user who has experienced this issue cannot access their PC.

Players get stuck in this part of the mission on mobile. 

![image](https://github.com/user-attachments/assets/b12ecaf3-390b-4a1f-953c-a735b272ad28)

**Comment by MemenTheMeme** [comment]
leveling a 4th account rn and i noticed this issue persists on pc as well. after killing zricera, i get teleported out of the room even with vindictive treasure as the active mission.
