### ISSUE TITLE
Ladder cannot be placed

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#687]
Log:
![Schermopname (13915)](https://github.com/user-attachments/assets/59005344-2a55-422e-8111-fe8577a440bb)

**Comment by MrGarrettFerret** [comment]
This is happening again. Same error. 
![image](https://github.com/user-attachments/assets/5c68a98d-c298-4284-a89a-37d801a25093)

**Comment by Leroy8888** [comment]
@MXKhronos just mentioned you as reminder. It's been an issue for quite awhile.
