### ISSUE TITLE
Intensifying skull burst

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#697]
The mod states that it stacks base fire rate per headshot. To a maximum of +50% base fire rate. It does not state how many stacks you need to maximize this effect.

However the display of the stacks above the ammo HUD goes beyond 50%, it in fact goes till 100%. **I assume** it adds it in increments based on the max percentage of the mod. Which would add 5% per headshot to the counter and then taking that 5% of the 50% from the mod ending up with 2.5% additional base fire rate per headshot until the max 50% as stated in the mod description.

It is a tad confusing so maybe it's just better to make it cap at 50% and just add increments of 2.5% instead of 5%.

**Comment by MXKhronos** [comment]
Oh, it goes from 0 to 100% to indicate max stack, but I will change it to your suggestion because it is clearer.

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/8024846b891db163c08e52410bc56eb374014ceb
