### ISSUE TITLE
1 time use emotes getting bugged after using it 

### ISSUE THREAD

**Issue by Emiraga36446** [HelixNebulaStudio/RiseOfTheDead#700]
When i use 1 time emotes such as open crate close crate emotes after the emote ends my character starts to get bugged stuck in place and not able to move with hes head spinning 360 every second like crazy 

İt also happens when entering bandit helicopter 

İt happens to me on mobile

**Comment by Leroy8888** [comment]
duplicate of #524 re-opened it.
