### ISSUE TITLE
The Bad side of new Slide System  in mobile (Enchancement)

### ISSUE THREAD

**Issue by Emiraga36446** [HelixNebulaStudio/RiseOfTheDead#702]
With the holding got added in you no more can slide easily in mobile and only way of being able to do it is by using 3 fingers at same time left thumb for going forward right thumb for crouch and and right point finger chancing the direction 

With the facts of mobile buttons being so small performing easy tasks such as sliding / slide jumping will be imposible for the mobile gameplay 

You can do this easily in computer but its pain in mobile 

Ways to Fix it 

Number 1 : Giving mobile players ability to customize button sizes and locations allowing us to finally set our game UI for a better gameplay by like making sliding button bigger And move it to better place and allowing us to make everything fitting 

Number 2 : give mobile players ability to still toggle crouch

Thats all

**Comment by MXKhronos** [comment]
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/474ffa7ed7573469bafb1430d77301aec9faef69
