### ISSUE TITLE
Roblox button style changed and it collides with ingame buttons in mobile

### ISSUE THREAD

**Issue by Emiraga36446** [HelixNebulaStudio/RiseOfTheDead#726]
They returned to new style again and buttons colldie 
![Screenshot_20241015_213646_Roblox](https://github.com/user-attachments/assets/cea08c1e-3932-478b-8fec-6d70eb77dc88)

**Comment by MrGarrettFerret** [comment]
This also happens on PC
![image](https://github.com/user-attachments/assets/0b8add68-9fbb-4543-9c84-1aaafabda0e4)

**Comment by MXKhronos** [comment]
Added initial checks to add margin from core ui.
