### ISSUE TITLE
Sliding in mobile Enchancement.

### ISSUE THREAD

**Issue by Emiraga36446** [HelixNebulaStudio/RiseOfTheDead#728]
After the recent camera change using joystick to control is harder and we cant do instant turns like pc which gives mobile less mobility over gameplay 

How to solve : turn sliding in mobile to old version where it would move to where you look and let pc stay same as it is now 
This would finally solve the war between mobile sliding and pc sliding

**Comment by MXKhronos** [comment]
I'm not sure what you mean, the current sliding mechanic allows you to turn with joystick or camera. 
I adjusted some turn sensitivity values for mobile to see if that feels better.

**Comment by Emiraga36446** [comment]
Using first person for rotating isnt a problem 

 but using joystick in 3rd person is pretty hard with the fact smaller screens are harder to control because s single move can change the whole direction also many of my friends struggle with turning left or right since we memorized only going forward while sliding also 

Just adding setting to switch the way of controlling sliding is much better but you are the owner so choice is yours 

Thanks for reading

**Comment by Emiraga36446** [comment]
+using camera to slide was much easier of a choice so thats why its also a much better option for mobile players since its much easier and not hard to control

**Comment by Emiraga36446** [comment]
One more thing 

If you try to shoot in 3rd person while sliding you have to use 3 fingers 1 for shooting 1 for joystick and 1 for sliding which is hella hard especially in tablet 

This is why changing mobiles sliding back to old version where İt would move where camera looks would be easier to use 

10 year olds would break their phones bc they cant shoot while sliding because of they need 3 fingers

**Comment by MXKhronos** [comment]
Added settings for camera slide lock.
