### ISSUE TITLE
Mission items can be deleted.

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#736]

**Comment by MXKhronos** [comment]
Which ones specifically? Because deleting mission items is possible now if you already completed the mission.

**Comment by MrPigZ** [comment]
Oh. I was weirded out that cultist note had a deletion option, so I hopped on an alt to check other items. I did not know that delete option should be vissible and that game would prevent deletion. I am too used to being able to delete everything on dev branch and I didn't want to softlock one of my alts. My bad
