### ISSUE TITLE
lost item and bug premium inventory

### ISSUE THREAD

**Issue by goblin-04** [HelixNebulaStudio/RiseOfTheDead#745]
My error is still not fixed, I lost some products and don't know why and how to get access to the premium inventory without buying a gamepass. Looking forward to receiving feedback from the developer, thanks for reading it

**Comment by MXKhronos** [comment]
Premium inventory requires premium member gamepass.

Please let me know which items you have lost and I'll add it back to your inventory.

**Comment by goblin-04** [comment]
I lost my diving glasses, rec 21, naughty cane ( all mods on it ) and all
the vector x mods ( lvl gun has been reset to 0 ), and hope you can fix the
premium inventory because I didn't buy it but have access to it. Thanks for
reading.

Vào 15:09 Th 2, 11 thg 11, 2024 Khronos ***@***.***> đã viết:
