### ISSUE TITLE
Some status effects do not work

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#772]
A few status effect don't seem to work and they also break a few different things. This issue only occurs if a player joins a server that has already been up for a little while. It does not occur if a player enters a new server.

The log shows the following warning;
![Schermopname (15041)](https://github.com/user-attachments/assets/d0cc54d4-ee93-431a-bc93-68aa92f19140)

A few sources with statuses that give this warning:
- Sugar rush of bloxy cola
- Slows from Heavy zombie attacks, this also breaks the entity
- Burps and gas cloud from Bloaters
- Explosive jumps - the explosions gets deleted / removed when it is in range of the player, also nullifying the damage output

**Comment by MrPigZ** [comment]
Player's status still not ready. 
This is brand new server. No player has reset. Mikael was first to join, Mr Pig Z was second to join.
https://github.com/user-attachments/assets/20795a7c-49d1-403c-a9f7-666a7a167913
