### ISSUE TITLE
my bug is not fixed 

### ISSUE THREAD

**Issue by goblin-04** [HelixNebulaStudio/RiseOfTheDead#778]
my lost item isn't fixed

**Comment by goblin-04** [comment]
im lost a diving goggle , rec 21( all mod on it), ladder, naughty cane(all mod on it), all mod on vector x, can developer restore them back to me. Thanks for reading.

**Comment by MXKhronos** [comment]
Sorry this took so long, I tried to restore your items, but it'll have to be replaced instead. You should see your missing items now and some additions for the delay. You can use the premium inventory too.
