### ISSUE TITLE
Script trying to load destroyed module? And Medical Breakthrough not working

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#781]
This in on windows store version of roblox but same issue does happen on normal roblox.
![image](https://github.com/user-attachments/assets/e5521129-76bd-4e5b-9336-cb70ced4c7fa)
![image](https://github.com/user-attachments/assets/9405ccea-264b-4843-9d98-ce02cb5fedd3)
![image](https://github.com/user-attachments/assets/46ffdcb7-7865-4061-85b1-5a9e18ed914c)
Mission is active and samples are in inventory. Game is not registering that player has arrived at clinic
![image](https://github.com/user-attachments/assets/c876af62-a745-44fb-aa66-fd488d2805b5)

**Comment by LooksMaxing** [comment]
Could you provide the output directly from roblox studio?

**Comment by MrPigZ** [comment]
I don't think I can
