### ISSUE TITLE
Witherers can spawn with a glitched santa hat

### ISSUE THREAD

**Issue by MrGarrettFerret** [HelixNebulaStudio/RiseOfTheDead#784]
![RobloxScreenShot20241207_184940476](https://github.com/user-attachments/assets/af700103-945e-4e4e-a476-28afb895a826)

**Comment by Leroy8888** [comment]
The commit refers to wraiths. The entity in this post is a witherer and it seems like they can still spawn with them after the patch.

This can also occur with VoN.

**Comment by MXKhronos** [comment]
Updated for Witherers and VoN too. Thanks.

**Comment by Leroy8888** [comment]
Still occurs

**Comment by MrPigZ** [comment]
![image](https://github.com/user-attachments/assets/f2adbbd5-2b86-4b7a-b2d6-35645c790533)
