### ISSUE TITLE
Slaughterfest missions are still here

### ISSUE THREAD

**Issue by wassagbruh** [HelixNebulaStudio/RiseOfTheDead#797]
Now, i don't really joined rise of the dead during the halloween event but i did check in and check out here and there.
![RobloxScreenShot20241221_201921673](https://github.com/user-attachments/assets/c56daca1-9bf3-4f70-bcf6-e59289e25a4c)

**Comment by APHOLLYONN** [comment]
Slaughterfest missions will probably stay until Frostivus 2024 releases
