### ISSUE TITLE
Burried Presents has breached the containment

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#811]
![image](https://github.com/user-attachments/assets/583eec66-ade4-4666-9c74-a122b0c4f23c)
![image](https://github.com/user-attachments/assets/0c6eac9e-50a4-47f3-bbc5-237a9639804e)
![image](https://github.com/user-attachments/assets/8378cab8-9cb3-40d4-bf4e-1c068b195146)

**Comment by Leroy8888** [comment]
when this does occur, if the player finds a tile with an item they can repeatedly unlock it to quickly finish it for rewards.

**Comment by APHOLLYONN** [comment]
![image](https://github.com/user-attachments/assets/7f131e98-d47a-4b7d-8658-ea94ecb7ea00)
be lucky you can even see the menu lol
