### ISSUE TITLE
Eternal Inferno and incendiary mod

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#82]
If the fire doesn't get to tick once before zombie dies the mission won't count the kill. Before if weapon had the mod and 1 shot zombie it got counted towards the mission.

I don't know if I have missed a memo.

**Comment by JakobCh** [comment]
Can confirm it doesn't count to the quest if you one shoot the zombie.
Personally I think you should actually have to kill them with the fire damage tho.
