### ISSUE TITLE
player become tom greyman

### ISSUE THREAD

**Issue by wassagbruh** [HelixNebulaStudio/RiseOfTheDead#824]
![RobloxScreenShot20241225_181831940](https://github.com/user-attachments/assets/fb912c0f-57aa-4a85-b5f8-f67c0b6ef720)
buggy update lol

**Comment by MrPigZ** [comment]
I haven't experienced this. Here are logs. Some people have reported that their gamepasses don't work.
![image](https://github.com/user-attachments/assets/ee22baec-0cde-4460-8cb6-70ef8c7bfe51)
![image](https://github.com/user-attachments/assets/ac274e45-af7c-4e79-ae79-3bd055e03ae7)

**Comment by wassagbruh** [comment]
![Capture](https://github.com/user-attachments/assets/9035520f-6ff6-4223-94e1-9536830a8e68)
yeah

**Comment by wassagbruh** [comment]
btw im still tom greyman

**Comment by wassagbruh** [comment]
@MrPigZ 
i found out the issue is caused by the night vision googles

**Comment by MrPigZ** [comment]
> @MrPigZ i found out the issue is caused by the night vision googles

This happened to me when I was wearing the snow sledge. Nightvision only causes this when you join existing server.

**Comment by rafaderren** [comment]
The snow sledge also causes this

**Comment by MrPigZ** [comment]
Snow sledge is still causing loading issues
