### ISSUE TITLE
Is the corrupt survival gamemodes even possible on solo?

### ISSUE THREAD

**Issue by wassagbruh** [HelixNebulaStudio/RiseOfTheDead#827]
I was grinding for the grand garand but I keep dying on wave 12 cause of the zombie being level 100+ like what the hell man?

**Comment by MrPigZ** [comment]
Yes, yes it is.

**Comment by wassagbruh** [comment]
> Yes, yes it is.

can you atleast tell me like an stratergy or something like that maybe an hint

**Comment by MrPigZ** [comment]
Get 5 max dmg mods on a melee and then play the survival like it's slaughterfest all over again.

**Comment by wassagbruh** [comment]
> Get 5 max dmg mods on a melee and then play the survival like it's slaughterfest all over again.

alright alright

**Comment by wassagbruh** [comment]
your stratergy sorta worked out, but i still died at wave 15

**Comment by rafaderren** [comment]
Bring Leather Boots with you and keep slide jumping

**Comment by wassagbruh** [comment]
> Bring Leather Boots with you and keep slide jumping

got it

**Comment by APHOLLYONN** [comment]
It's beyond possible, use a sniper and recycler for later waves
![image](https://github.com/user-attachments/assets/3577bbe5-0535-443f-8564-56854aaf304b)
also wave 200 activities in dev branch

**Comment by wassagbruh** [comment]
> It's beyond possible, use a sniper and recycler for later waves ![image](https://private-user-images.githubusercontent.com/186779970/398633221-3577bbe5-0535-443f-8564-56854aaf304b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODg3MDEsIm5iZiI6MTczNTE4ODQwMSwicGF0aCI6Ii8xODY3Nzk5NzAvMzk4NjMzMjIxLTM1NzdiYmU1LTA1MzUtNDQzZi04NTY0LTU2ODU0YWFmMzA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwNDQ2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTI5OTZhMDJhZWViYzY2ZTE3NzVkNTQ1NzYxNDQyMTA0YThiOGM5YzVhNGIwZTIxNmYxZWFiOWVhZTYyNTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N4L5kSgBVJ7DQFJJiuIr8Slc_18Rx8zOxQDQj_QfdXs) also wave 200 activities in dev branch (the level stacks to an ungodly amount after enough waves have passed)

dude i got the sniper in crafting

**Comment by wassagbruh** [comment]
should i keep the issue open for other players like me having issues with the corrupted levels?

**Comment by wassagbruh** [comment]
> Close it, its not really an issue its a skill issue and they can adapt themselves.

alright
