### ISSUE TITLE
Mission Pass gets bugged after losing connection while a correct tile is being opened in Buried Presents

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#840]
If you get something right the ui will be stucked to traveling, after reopening the ui it will show youre correct but still think youre not done with the game while this bug is present. 
If I open another correct tile after all 4 tiles are opened in Buried Presents the game will give me 1 level
Levels do not sync with levels obtained from missions until the player rejoins (might be an unrelated bug actually)
I lost one Frostivus Present 2024 from this
And **rejoining does not fix this bug at all**
![image](https://github.com/user-attachments/assets/fe3fe207-0714-4454-a79d-94912e9305a5)
![image](https://github.com/user-attachments/assets/13ba91fe-86c5-4ec8-83d8-3b6acdaf1233)

**Comment by MrPigZ** [comment]
No disconnects needed.
![image](https://github.com/user-attachments/assets/bb130b8f-c095-47a2-832f-cc5b7ae5e7fb)

![image](https://github.com/user-attachments/assets/14cd8ed6-e8e8-4be1-a90e-7de9b523ba20)
