### ISSUE TITLE
Frostivus skin permanent does not display on the garand

### ISSUE THREAD

**Issue by APHOLLYONN** [HelixNebulaStudio/RiseOfTheDead#863]

**Comment by APHOLLYONN** [comment]
it doesnt display on the boomerang either

**Comment by Leroy8888** [comment]
Do keep in mind, if you applied a color or anything like it before applying a skin perm, the color will override the skin perm.

I cannot replicate the issue discribed here. Both my boomerang and garand have it applied on it and display it.
![Schermopname (15317)](https://github.com/user-attachments/assets/7d6486dc-4043-4417-a40f-3413cfcc32b1)
Note: I removed the color of the scope on the garand to check if the skin was visible.

**Comment by APHOLLYONN** [comment]
huh, good to know
