### ISSUE TITLE
Remove tax on the M9

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#876]
Gonna make a bold suggestion here to remove the tax on the M9.

The M9 is currently the only weapon in-game which cannot be obtained normally and it is only accessible during a short time window in events. Trading is currently the easiest and most reliable way to get them.

The M9 is relatively easy to obtain from easter eggs, however some countries restrict trading lootboxes. Without the use of a VPN a player without premium would have to either grind it themselves or compensate for the insane gold tax. On top of this it's not exactly easy to find people selling these seasonal lootboxes nowadays, plenty of people have them, but there aren't many sellers. During this event, where it can be obtained at a 1.3% chance from 2019 gifts, it would be especially difficult to obtain it for a F2P user.

So by removing the tax for M9 it would allow other players to obtained it more easily. Could be a QoL for F2P users. It should be noted that the M9 would be the only exception to this change, as there currently isn't (any obtainable) M9 BP to get it from.

**Comment by APHOLLYONN** [comment]
Or re-add the m9 or its blueprint to SOME drop source? the blueprint already exists but was removed for some reason im not aware of.
