### ISSUE TITLE
Board missions dropping Desert Eagle Parts

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#9]
Mission `17`, `26` and `71` now drops `deagleparts`.

Dialogues won't let you complete the mission if you don't have inventory space to collect the items.

**Comment by Leroy8888** [comment]
Seems to work fine. Although, it's currently unclear to me when players get introduced to the mission board.

**Comment by MXKhronos** [comment]
> Although, it's currently unclear to me when players get introduced to the mission board and get access to the parts

The mission A Good Deal (16) was to introduce board missions to the players (used to be dailies). I'll change the dialogues abit to state how some board mission has unique rewards.

**Comment by ClownCarsXD** [comment]
Khronos ROTD has been my favorite roblox game for a few years now. Thank you for giving so many awesome memories this game was the shit back in 2020 and I hope to see it grow back to what it was a few years back. Please Don't stop development I want to see the end of the story, lore, etc. 

Thank You Khronos <3
- Reddhatter1307sbro
