### ISSUE TITLE
Can't reject npc in mission Another Survivor

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#90]
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/135a581c-d752-4e1d-bf33-0a612a505691)

**Comment by MXKhronos** [comment]
Maybe you were doing the mission for the first time in a new save? Doing Another Survivor for the first time will no give you the option to reject them.
